# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_PACKAGES += \
	libexcal_color_ctrl_plugin \
	libexcal_debug_display_plugin \
	libexcal_exposure_ctrl_plugin \
	libexcal_face_detector_plugin \
	libexcal_flicker_detector_plugin \
	libexcal_focus_stats_conv_plugin \
	libexcal_food_comp_plugin \
	libexcal_food_detector_plugin \
	libexcal_hal_ctrl_plugin \
	libexcal_hdr_plugin \
	libexcal_idt_ctrl_plugin \
	libexcal_image_conv_plugin \
	libexcal_iq_ctrl_plugin \
	libexcal_jpeg_enc_plugin \
	libexcal_lens_ctrl_plugin \
	libexcal_motion_estimation_plugin \
	libexcal_multiframe_nr_plugin \
	libexcal_object_tracker_plugin \
	libexcal_req_ctrl_plugin \
	libexcal_scene_detector_plugin \
	libexcal_snapshot_ctrl_plugin \
	libexcal_splitter_plugin \
	libexcal_stream_ctrl_plugin \
	libdrmwvmplugin \
	libGLES_android_so_32 \
	camera.msm8994 \
	fingerprint_msm8994_so_32 \
	touch_cover_so_32 \
	libMcClient_so_32 \
	libMcRegistry_so_32 \
	libMiscTAApi_so_32 \
	libMiscTaAccessor_so_32 \
	libQWiFiSoftApCfg_so_32 \
	libWnnEngDic_so_32 \
	libWnnJpnDic_so_32 \
	lib_asb_tee_so_32 \
	lib_fpc_tac_shared_so_32 \
	libaudiohookclient_so_32 \
	libbt-aptX-ARM-4.2.2 \
	libcacao_client \
	libcacao_common \
	libcacao_imgproc \
	libcacao_jpeg \
	libcacao_service \
	libcacao_system \
	libcamera_clientsemc_so_32 \
	libcameraextensionclient_so_32 \
	libcameraextensionjni_so_32 \
	libcameraextensionservice_so_32 \
	libcameralight_so_32 \
	libcammw \
	libcom_fingerprints_service_so_32 \
	libcrashlevelmatrix_so_32 \
	libcrashmonitorclient_so_32 \
	libcrashmonitorjni_so_32 \
	libcredential-manager-service_so_32 \
	libcurl_so_32 \
	libdashplayer_so_32 \
	libdatawasherjni_so_32 \
	libdeqp_somc_so_32 \
	libdevice_security_so_32 \
	libdisplayservice_so_32 \
	libdumpframework_so_32 \
	libebtc_so_32 \
	libexcal_core \
	libexcal_legacy \
	libexcal_pal \
	libexcal_system \
	libextended_boot_lock_so_32 \
	libextmedia_jni_so_32 \
	libfrpflag_so_32 \
	libgaanalytics_so_32 \
	libgssapi_kerberos \
	libhdcprx_module_so_32 \
	libhdcptx_module_so_32 \
	libhscomp_so_32 \
	libhscomp_jni_so_32 \
	libidd_so_32 \
	libiddjni_so_32 \
	libimageprocessorjni \
	libjni_gallery_eglfence \
	libjni_gallery_filters \
	libjni_gallery_jpegstream \
	libldacBT_enc \
	liblights-core_so_32 \
	libmiscta_so_32 \
	libmm-qcamera \
	libmmcamera_interface \
	libmmjpeg_interface \
	libnfc-config_so_32 \
	liboemcrypto \
	libpf_so_32 \
	libpfter_so_32 \
	libpin-cache_so_32 \
	libplstorage_so_32 \
	libprotobuf-c_so_32 \
	libprotobuf-cpp-2_3_0-lite_so_32 \
	libqcmediaplayer_so_32 \
	libqomx_core \
	libqsap_sdk_so_32 \
	libregionalization_so_32 \
	librmnetctl_so_32 \
	libscdclient_so_32 \
	libservicemenu_so_32 \
	libsnappy_so_32 \
	libsomc_alfort \
	libsomc_alfortrsc \
	libsomc_bordeaux \
	libsomc_bordeauxrsc \
	libsomc_canele \
	libsomc_canelersc \
	libsomc_chokoballcmn \
	libsomc_chokoballpal \
	libsomc_marble \
	libsomc_marblersc \
	libsomc_melonpan \
	libsomc_melonpanrsc \
	libsomc_mugichoco \
	libsomc_mugichocorsc \
	libsomc_raisin \
	libsomc_raisinrsc \
	libsomc_spica \
	libsomc_spicarsc \
	libsomc_thermal_so_32 \
	libsomc_toppo \
	libsomc_topporsc \
	libsomc_yummy \
	libsomc_yummyrsc \
	libsomcavextensionsimpl_so_32 \
	libsomcmediahttp_so_32 \
	libsony_fooddetect \
	libsony_naruto \
	libsonydseehxwrapper_so_32 \
	libstagefright_hdcp_so_32 \
	libstagefright_pf_so_32 \
	libstagefright_soft_somcalacdec \
	libstagefright_soft_somcdsddec \
	libstartup-reason_so_32 \
	libsuntory_so_32 \
	libsuntory_utils_so_32 \
	libswiqisettinghelper_so_32 \
	libsys-utils_so_32 \
	libsysinfo_so_32 \
	libsysinfo_jni_so_32 \
	clearpad_so_32 \
	libta_so_32 \
	libthermal_engine_so_32 \
	libthermal_engine_jni_so_32 \
	libtinyxml_so_32 \
	libtinyxml2_so_32 \
	libtlcore_so_32 \
	libtpm_so_32 \
	libwfdhdcpcp_so_32 \
	libwnndict_so_32 \
	libsonypostprocbundle \
	libsonysweffect \
	eglSubDriverAndroid_so_32 \
	libEGL_adreno_so_32 \
	libGLESv1_CM_adreno_so_32 \
	libGLESv2_adreno_so_32 \
	libQTapGLES_so_32 \
	libq3dtools_adreno_so_32 \
	libq3dtools_esx_so_32 \
	gatekeeper_msm8994_so_32 \
	lib-dplmedia_so_32 \
	lib-ims-rcscmjni_so_32 \
	lib-imsSDP_so_32 \
	lib-imscamera_so_32 \
	lib-imsdpl_so_32 \
	lib-imsqimf_so_32 \
	lib-imsrcs_so_32 \
	lib-imsrcscm_so_32 \
	lib-imsrcscmclient_so_32 \
	lib-imsrcscmservice_so_32 \
	lib-imss_so_32 \
	lib-imsvt_so_32 \
	lib-imsxml_so_32 \
	lib-rcsimssjni_so_32 \
	lib-rcsjni_so_32 \
	lib-rtpcommon_so_32 \
	lib-rtpcore_so_32 \
	lib-rtpdaemoninterface_so_32 \
	lib-rtpsl_so_32 \
	lib-sec-disp_so_32 \
	libC2D2_so_32 \
	libCB_so_32 \
	libChamomilePA_so_32 \
	libExtendedExtractor_so_32 \
	libFIDOKeyProvisioning_so_32 \
	libFidoCrypto_so_32 \
	libFidoCryptoJNI_so_32 \
	libFileMux_so_32 \
	libFlacSwDec_so_32 \
	libI420colorconvert_so_32 \
	libOmxAacDec_so_32 \
	libOmxAmrwbplusDec_so_32 \
	libOmxEvrcDec \
	libOmxMux_so_32 \
	libOmxQcelp13Dec \
	libOmxWmaDec_so_32 \
	libOpenCL_so_32 \
	libQSEEComAPI_so_32 \
	libQtiTether_so_32 \
	libRSDriver_adreno_so_32 \
	libSampleAuthJNI_so_32 \
	libSecureSampleAuthJNI_so_32 \
	libSecureUILib_so_32 \
	libStDrvInt_so_32 \
	libSubSystemShutdown \
	libTimeService_so_32 \
	libWVStreamControlAPI_L1 \
	libacdb-fts_so_32 \
	libacdbloader_so_32 \
	libacdbmapper_so_32 \
	libacdbrtac_so_32 \
	libactuator_ad5823 \
	libactuator_ad5823_camcorder \
	libactuator_ad5823_camera \
	libactuator_bu64244gwz \
	libactuator_bu64244gwz_camcorder \
	libactuator_bu64244gwz_camera \
	libactuator_dw9714 \
	libactuator_dw9714_camcorder \
	libactuator_dw9714_camera \
	libactuator_dw9716 \
	libactuator_dw9716_camcorder \
	libactuator_dw9716_camera \
	libactuator_dw9761b \
	libactuator_dw9761b_camcorder \
	libactuator_dw9761b_camera \
	libactuator_lc898122 \
	libactuator_lc898122_camcorder \
	libactuator_lc898122_camera \
	libactuator_lc898212xd \
	libactuator_lc898212xd_camcorder \
	libactuator_lc898212xd_camera \
	libactuator_ov8825 \
	libactuator_ov8825_camcorder \
	libactuator_ov8825_camera \
	libactuator_rohm_bu64243gwz \
	libactuator_rohm_bu64243gwz_camcorder \
	libactuator_rohm_bu64243gwz_camera \
	libadiertac_so_32 \
	libadm \
	libadreno_utils_so_32 \
	libadsprpc_so_32 \
	libalarmservice_jni_so_32 \
	libasn1cper_so_32 \
	libasn1crt_so_32 \
	libasn1crtx_so_32 \
	libaudcal_so_32 \
	libaudioalsa_so_32 \
	libavenhancements_so_32 \
	libbccQTI_so_32 \
	libc2d30-a3xx_so_32 \
	libc2d30-a4xx_so_32 \
	libchromatix_s5k3m2xx_common \
	libchromatix_s5k3m2xx_cpp_hfr_120 \
	libchromatix_s5k3m2xx_cpp_hfr_60 \
	libchromatix_s5k3m2xx_cpp_hfr_90 \
	libchromatix_s5k3m2xx_cpp_liveshot \
	libchromatix_s5k3m2xx_cpp_preview \
	libchromatix_s5k3m2xx_cpp_snapshot \
	libchromatix_s5k3m2xx_cpp_video \
	libchromatix_s5k3m2xx_cpp_video_4k \
	libchromatix_s5k3m2xx_default_video \
	libchromatix_s5k3m2xx_hfr_120 \
	libchromatix_s5k3m2xx_hfr_60 \
	libchromatix_s5k3m2xx_hfr_90 \
	libchromatix_s5k3m2xx_liveshot \
	libchromatix_s5k3m2xx_postproc \
	libchromatix_s5k3m2xx_preview \
	libchromatix_s5k3m2xx_snapshot \
	libchromatix_s5k3m2xx_video_4k \
	libcne_so_32 \
	libcneapiclient_so_32 \
	libcneqmiutils_so_32 \
	libconfigdb_so_32 \
	libconnctrl_so_32 \
	libdataitems_so_32 \
	libdiag_so_32 \
	libdisp-aba_so_32 \
	libdpmctmgr_so_32 \
	libdpmfdmgr_so_32 \
	libdpmframework_so_32 \
	libdpmnsrm_so_32 \
	libdpmtcm_so_32 \
	libdrc \
	libdrmfs_so_32 \
	libdrmtime_so_32 \
	libdsi_netctrl_so_32 \
	libdsutils_so_32 \
	libextendedremotedisplay_so_32 \
	libfastcvadsp_stub \
	libfastcvopt \
	libflash_pmic \
	libflp_so_32 \
	libgdtap_so_32 \
	libgeofence_so_32 \
	libgsl_so_32 \
	libidl_so_32 \
	libimscamera_jni_so_32 \
	libimsmedia_jni_so_32 \
	libizat_core_so_32 \
	libjpegdhw \
	libjpegdmahw \
	libjpegehw \
	liblbs_core_so_32 \
	liblistensoundmodel2 \
	libllvm-glnext_so_32 \
	libllvm-qcom_so_32 \
	libloc_ext_so_32 \
	liblocationservice_so_32 \
	liblocationservice_glue_so_32 \
	liblowi_client_so_32 \
	liblowi_wifihal_so_32 \
	liblowi_wifihal_nl_so_32 \
	liblqe_so_32 \
	libmdmdetect_so_32 \
	libmdsprpc_so_32 \
	libmm-abl-oem_so_32 \
	libmm-abl_so_32 \
	libmm-als_so_32 \
	libmm-color-convertor_so_32 \
	libmm-disp-apis_so_32 \
	libmm-hdcpmgr_so_32 \
	libmm-qdcm_so_32 \
	libmmQSM \
	libmmcamera2_c2d_module \
	libmmcamera2_cpp_module \
	libmmcamera2_frame_algorithm \
	libmmcamera2_iface_modules \
	libmmcamera2_imglib_modules \
	libmmcamera2_is \
	libmmcamera2_isp_modules \
	libmmcamera2_pp_buf_mgr \
	libmmcamera2_pproc_modules \
	libmmcamera2_q3a_core_so_32 \
	libmmcamera2_sensor_debug_so_32 \
	libmmcamera2_sensor_modules \
	libmmcamera2_stats_algorithm_so_32 \
	libmmcamera2_stats_modules \
	libmmcamera2_vpe_module \
	libmmcamera2_wnr_module \
	libmmcamera_cac2_lib \
	libmmcamera_chromaflash_lib \
	libmmcamera_dw9761b_eeprom \
	libmmcamera_eeprom_util \
	libmmcamera_eztune_module \
	libmmcamera_faceproc \
	libmmcamera_hdr_gb_lib \
	libmmcamera_imglib \
	libmmcamera_imx258_gt24c16_eeprom \
	libmmcamera_isp_abf44 \
	libmmcamera_isp_bcc44 \
	libmmcamera_isp_be_stats44 \
	libmmcamera_isp_bf_scale_stats46 \
	libmmcamera_isp_bf_stats44 \
	libmmcamera_isp_bg_stats46 \
	libmmcamera_isp_bhist_stats44 \
	libmmcamera_isp_bpc44 \
	libmmcamera_isp_chroma_enhan40 \
	libmmcamera_isp_chroma_suppress40 \
	libmmcamera_isp_clamp_encoder40 \
	libmmcamera_isp_clamp_video40 \
	libmmcamera_isp_clamp_viewfinder40 \
	libmmcamera_isp_clf46 \
	libmmcamera_isp_color_correct46 \
	libmmcamera_isp_color_xform_encoder46 \
	libmmcamera_isp_color_xform_video46 \
	libmmcamera_isp_color_xform_viewfinder46 \
	libmmcamera_isp_cs_stats46 \
	libmmcamera_isp_demosaic44 \
	libmmcamera_isp_demux40 \
	libmmcamera_isp_fovcrop_encoder46 \
	libmmcamera_isp_fovcrop_video46 \
	libmmcamera_isp_fovcrop_viewfinder46 \
	libmmcamera_isp_gamma44 \
	libmmcamera_isp_gic46 \
	libmmcamera_isp_gtm46 \
	libmmcamera_isp_hdr46 \
	libmmcamera_isp_hdr_be_stats46 \
	libmmcamera_isp_ihist_stats46 \
	libmmcamera_isp_linearization40 \
	libmmcamera_isp_ltm44 \
	libmmcamera_isp_mce40 \
	libmmcamera_isp_mesh_rolloff44 \
	libmmcamera_isp_pedestal_correct46 \
	libmmcamera_isp_rs_stats46 \
	libmmcamera_isp_scaler_encoder46 \
	libmmcamera_isp_scaler_video46 \
	libmmcamera_isp_scaler_viewfinder46 \
	libmmcamera_isp_sce40 \
	libmmcamera_isp_sub_module \
	libmmcamera_isp_wb46 \
	libmmcamera_llvd \
	libmmcamera_onsemi_cat24c32_eeprom \
	libmmcamera_optizoom_lib \
	libmmcamera_ov4688_eeprom \
	libmmcamera_pdaf \
	libmmcamera_pdaf_v3 \
	libmmcamera_pdafcamif \
	libmmcamera_ppbase_module \
	libmmcamera_sony_imx214_eeprom \
	libmmcamera_sonyimx135_eeprom \
	libmmcamera_stillmore_lib \
	libmmcamera_tintless_algo \
	libmmcamera_tintless_bg_pca_algo \
	libmmcamera_trueportrait_lib \
	libmmcamera_tuning \
	libmmcamera_ubifocus_lib \
	libmmcamera_vpu_module \
	libmmhttpstack_so_32 \
	libmmiipstreammmihttp_so_32 \
	libmmipl \
	libmmipstreamaal_so_32 \
	libmmipstreamnetwork_so_32 \
	libmmipstreamsourcehttp_so_32 \
	libmmipstreamutils_so_32 \
	libmmjpeg \
	libmmosal_so_32 \
	libmmparser_so_32 \
	libmmparser_lite_so_32 \
	libmmqjpeg_codec \
	libmmqjpegdma \
	libmmrtpdecoder_so_32 \
	libmmrtpencoder_so_32 \
	libmmwfdinterface_so_32 \
	libmmwfdsinkinterface_so_32 \
	libmmwfdsrcinterface_so_32 \
	libnative_audio_latency_jni \
	libnetmgr_so_32 \
	liboemcamera \
	libois_lc898122 \
	libperipheral_client_so_32 \
	libpreload-me_so_32 \
	libqcci_legacy_so_32 \
	libqct_resampler \
	libqdi_so_32 \
	libqdp_so_32 \
	libqmi_so_32 \
	libqmi_cci_so_32 \
	libqmi_client_helper_so_32 \
	libqmi_client_qmux_so_32 \
	libqmi_common_so_so_32 \
	libqmi_csi_so_32 \
	libqmi_encdec_so_32 \
	libqmiservices_so_32 \
	libqomx_jpegdec \
	libqomx_jpegenc \
	libqomx_jpegenc_pipe \
	libqti-at_so_32 \
	libqti-gt_so_32 \
	libqti-perfd-client_so_32 \
	libqti_performance_so_32 \
	libquipc_os_api_so_32 \
	librcc_so_32 \
	libril-qc-ltedirectdisc_so_32 \
	libril-qc-qmi-1_so_32 \
	libril-qc-radioconfig_so_32 \
	librilqmiservices_so_32 \
	librpmb_so_32 \
	librs_adreno_so_32 \
	librs_adreno_sha1_so_32 \
	libscale_so_32 \
	libsd_sdk_display_so_32 \
	libsecureui_so_32 \
	libsecureui_svcsock_so_32 \
	libsecureuisvc_jni_so_32 \
	libsensor1_so_32 \
	libsensor_reg_so_32 \
	libsettings_so_32 \
	libslimclient_so_32 \
	libsmemlog_so_32 \
	libsregex \
	libssd_so_32 \
	libsubsystem_control_so_32 \
	libsurround_3mic_proc \
	libsystem_health_mon_so_32 \
	libthermalclient_so_32 \
	libtime_genoff_so_32 \
	libts_detected_face_jni \
	libts_face_beautify_jni \
	libtzdrmgenprov_so_32 \
	libulp2_so_32 \
	libvendorconn_so_32 \
	libvoice-svc_so_32 \
	libwfdavenhancements_so_32 \
	libwfdcommonutils_so_32 \
	libwfdmmsink_so_32 \
	libwfdmmsrc_so_32 \
	libwfdmmutils_so_32 \
	libwfdnative_so_32 \
	libwfdrtsp_so_32 \
	libwfdservice_so_32 \
	libwfdsm_so_32 \
	libwfduibcinterface_so_32 \
	libwfduibcsink_so_32 \
	libwfduibcsinkinterface_so_32 \
	libwfduibcsrc_so_32 \
	libwfduibcsrcinterface_so_32 \
	libwms_so_32 \
	libwqe_so_32 \
	libwvdrm_L1 \
	libwvm \
	libxml_so_32 \
	libxt_native_so_32 \
	libxtadapter_so_32 \
	libxtwifi_ulp_adaptor_so_32 \
	libdrmclearkeyplugin_so_32 \
	libwvdrmengine \
	libapps_mem_heap \
	libdspCV_skel \
	libfastcvadsp \
	libfastcvadsp_skel \
	sensors_ssc_so_32 \
	libqcbassboost \
	libqcreverb \
	libqcvirt \
	libGLES_android_so_64 \
	fingerprint_msm8994_so_64 \
	touch_cover_so_64 \
	libMcClient_so_64 \
	libMcRegistry_so_64 \
	libMiscTAApi_so_64 \
	libMiscTaAccessor_so_64 \
	libQWiFiSoftApCfg_so_64 \
	libWnnEngDic_so_64 \
	libWnnJpnDic_so_64 \
	lib_asb_tee_so_64 \
	lib_fpc_tac_shared_so_64 \
	lib_get_secure_mode \
	libaudiohookclient_so_64 \
	libcamera_clientsemc_so_64 \
	libcameraextensionclient_so_64 \
	libcameraextensionjni_so_64 \
	libcameraextensionservice_so_64 \
	libcameralight_so_64 \
	libcom_fingerprints_service_so_64 \
	libcrashlevelmatrix_so_64 \
	libcrashmonitorclient_so_64 \
	libcrashmonitorjni_so_64 \
	libcredential-manager-service_so_64 \
	libcrypto_fips \
	libcurl_so_64 \
	libdashplayer_so_64 \
	libdatawasherjni_so_64 \
	libdebugmenulight \
	libdeqp_somc_so_64 \
	libdevice_security_so_64 \
	libdhcpcd \
	libdisplayservice_so_64 \
	libdumpframework_so_64 \
	libebt_802_3 \
	libebt_among \
	libebt_arp \
	libebt_arpreply \
	libebt_ip \
	libebt_ip6 \
	libebt_limit \
	libebt_log \
	libebt_mark \
	libebt_mark_m \
	libebt_nat \
	libebt_nflog \
	libebt_pkttype \
	libebt_redirect \
	libebt_standard \
	libebt_stp \
	libebt_ulog \
	libebt_vlan \
	libebtable_broute \
	libebtable_filter \
	libebtable_nat \
	libebtc_so_64 \
	libextended_boot_lock_so_64 \
	libextmedia_jni_so_64 \
	libfilterpack_facedetect \
	libfrpflag_so_64 \
	libgaanalytics_so_64 \
	libhdcprx_module_so_64 \
	libhdcptx_module_so_64 \
	libhscomp_so_64 \
	libhscomp_jni_so_64 \
	libidd_so_64 \
	libiddjni_so_64 \
	libjansson \
	libkeystore_fips \
	liblights-core_so_64 \
	libloc_api_v02 \
	libloc_ds_api \
	libmiscta_so_64 \
	libnfc-config_so_64 \
	libpf_so_64 \
	libpfter_so_64 \
	libpin-cache_so_64 \
	libplstorage_so_64 \
	libprotobuf-c_so_64 \
	libprotobuf-cpp-2_3_0-lite_so_64 \
	libqcmediaplayer_so_64 \
	libqsap_sdk_so_64 \
	libregionalization_so_64 \
	librmnetctl_so_64 \
	libscdclient_so_64 \
	libservicemenu_so_64 \
	libsnappy_so_64 \
	libsomc_thermal_so_64 \
	libsomcavextensionsimpl_so_64 \
	libsomcmediahttp_so_64 \
	libsomcwifi-service \
	libsonydseehxwrapper_so_64 \
	libstagefright_hdcp_so_64 \
	libstagefright_pf_so_64 \
	libstartup-reason_so_64 \
	libsuntory_so_64 \
	libsuntory_utils_so_64 \
	libswiqisettinghelper_so_64 \
	libsys-utils_so_64 \
	libsysinfo_so_64 \
	libsysinfo_jni_so_64 \
	clearpad_so_64 \
	libta_so_64 \
	libtee \
	libthermal_engine_so_64 \
	libthermal_engine_jni_so_64 \
	libtinyxml_so_64 \
	libtinyxml2_so_64 \
	libtlcore_so_64 \
	libtpm_so_64 \
	libttscompat \
	libttspico \
	libwfdhdcpcp_so_64 \
	libwnndict_so_64 \
	eglSubDriverAndroid_so_64 \
	libEGL_adreno_so_64 \
	libGLESv1_CM_adreno_so_64 \
	libGLESv2_adreno_so_64 \
	libQTapGLES_so_64 \
	libq3dtools_adreno_so_64 \
	libq3dtools_esx_so_64 \
	flp.default \
	gatekeeper_msm8994_so_64 \
	lib-dplmedia_so_64 \
	lib-ims-rcscmjni_so_64 \
	lib-imsSDP_so_64 \
	lib-imscamera_so_64 \
	lib-imsdpl_so_64 \
	lib-imsqimf_so_64 \
	lib-imsrcs_so_64 \
	lib-imsrcscm_so_64 \
	lib-imsrcscmclient_so_64 \
	lib-imsrcscmservice_so_64 \
	lib-imss_so_64 \
	lib-imsvt_so_64 \
	lib-imsxml_so_64 \
	lib-rcsimssjni_so_64 \
	lib-rcsjni_so_64 \
	lib-rtpcommon_so_64 \
	lib-rtpcore_so_64 \
	lib-rtpdaemoninterface_so_64 \
	lib-rtpsl_so_64 \
	lib-sec-disp_so_64 \
	libC2D2_so_64 \
	libCB_so_64 \
	libChamomilePA_so_64 \
	libCommandSvc \
	libExtendedExtractor_so_64 \
	libFIDOKeyProvisioning_so_64 \
	libFidoCrypto_so_64 \
	libFidoCryptoJNI_so_64 \
	libFileMux_so_64 \
	libFlacSwDec_so_64 \
	libI420colorconvert_so_64 \
	libOmxAacDec_so_64 \
	libOmxAmrwbplusDec_so_64 \
	libOmxMux_so_64 \
	libOmxWmaDec_so_64 \
	libOpenCL_so_64 \
	libQSEEComAPI_so_64 \
	libQtiTether_so_64 \
	libRSDriver_adreno_so_64 \
	libSampleAuthJNI_so_64 \
	libSecureSampleAuthJNI_so_64 \
	libSecureUILib_so_64 \
	libStDrvInt_so_64 \
	libTimeService_so_64 \
	libUserAgent \
	libacdb-fts_so_64 \
	libacdbloader_so_64 \
	libacdbmapper_so_64 \
	libacdbrtac_so_64 \
	libadiertac_so_64 \
	libadreno_utils_so_64 \
	libadsprpc_so_64 \
	libalarmservice_jni_so_64 \
	libasn1cper_so_64 \
	libasn1crt_so_64 \
	libasn1crtx_so_64 \
	libaudcal_so_64 \
	libaudioalsa_so_64 \
	libavenhancements_so_64 \
	libbccQTI_so_64 \
	libc2d30-a3xx_so_64 \
	libc2d30-a4xx_so_64 \
	libcne_so_64 \
	libcneapiclient_so_64 \
	libcneqmiutils_so_64 \
	libconfigdb_so_64 \
	libconnctrl_so_64 \
	libdataitems_so_64 \
	libdiag_so_64 \
	libdisp-aba_so_64 \
	libdpmctmgr_so_64 \
	libdpmfdmgr_so_64 \
	libdpmframework_so_64 \
	libdpmnsrm_so_64 \
	libdpmtcm_so_64 \
	libdrmfs_so_64 \
	libdrmtime_so_64 \
	libdsi_netctrl_so_64 \
	libdsutils_so_64 \
	libextendedremotedisplay_so_64 \
	libflp_so_64 \
	libgdtap_so_64 \
	libgeofence_so_64 \
	libgsl_so_64 \
	libidl_so_64 \
	libimscamera_jni_so_64 \
	libimsmedia_jni_so_64 \
	libizat_core_so_64 \
	liblbs_core_so_64 \
	libllvm-glnext_so_64 \
	libllvm-qcom_so_64 \
	libloc_ext_so_64 \
	liblocationservice_so_64 \
	liblocationservice_glue_so_64 \
	liblowi_client_so_64 \
	liblowi_wifihal_so_64 \
	liblowi_wifihal_nl_so_64 \
	liblqe_so_64 \
	libmdmdetect_so_64 \
	libmdsprpc_so_64 \
	libmm-abl-oem_so_64 \
	libmm-abl_so_64 \
	libmm-als_so_64 \
	libmm-color-convertor_so_64 \
	libmm-disp-apis_so_64 \
	libmm-hdcpmgr_so_64 \
	libmm-qdcm_so_64 \
	libmmcamera2_q3a_core_so_64 \
	libmmcamera2_sensor_debug_so_64 \
	libmmcamera2_stats_algorithm_so_64 \
	libmmhttpstack_so_64 \
	libmmiipstreammmihttp_so_64 \
	libmmipstreamaal_so_64 \
	libmmipstreamnetwork_so_64 \
	libmmipstreamsourcehttp_so_64 \
	libmmipstreamutils_so_64 \
	libmmosal_so_64 \
	libmmparser_so_64 \
	libmmparser_lite_so_64 \
	libmmrtpdecoder_so_64 \
	libmmrtpencoder_so_64 \
	libmmwfdinterface_so_64 \
	libmmwfdsinkinterface_so_64 \
	libmmwfdsrcinterface_so_64 \
	libnetmgr_so_64 \
	libperipheral_client_so_64 \
	libpreload-me_so_64 \
	libqcci_legacy_so_64 \
	libqcmaputils \
	libqdi_so_64 \
	libqdp_so_64 \
	libqmi_so_64 \
	libqmi_cci_so_64 \
	libqmi_client_helper_so_64 \
	libqmi_client_qmux_so_64 \
	libqmi_common_so_so_64 \
	libqmi_csi_so_64 \
	libqmi_encdec_so_64 \
	libqmiservices_so_64 \
	libqti-at_so_64 \
	libqti-gt_so_64 \
	libqti-perfd-client_so_64 \
	libqti_performance_so_64 \
	libquipc_os_api_so_64 \
	librcc_so_64 \
	libril-qc-ltedirectdisc_so_64 \
	libril-qc-qmi-1_so_64 \
	libril-qc-radioconfig_so_64 \
	librilqmiservices_so_64 \
	librpmb_so_64 \
	librs_adreno_so_64 \
	librs_adreno_sha1_so_64 \
	libscale_so_64 \
	libsd_sdk_display_so_64 \
	libsecureui_so_64 \
	libsecureui_svcsock_so_64 \
	libsecureuisvc_jni_so_64 \
	libsensor1_so_64 \
	libsensor_reg_so_64 \
	libsettings_so_64 \
	libslimclient_so_64 \
	libsmemlog_so_64 \
	libssd_so_64 \
	libsubsystem_control_so_64 \
	libsystem_health_mon_so_64 \
	libthermalclient_so_64 \
	libthermalioctl \
	libtime_genoff_so_64 \
	libtzdrmgenprov_so_64 \
	libulp2_so_64 \
	libvendorconn_so_64 \
	libvoice-svc_so_64 \
	libwfdavenhancements_so_64 \
	libwfdcommonutils_so_64 \
	libwfdmmsink_so_64 \
	libwfdmmsrc_so_64 \
	libwfdmmutils_so_64 \
	libwfdnative_so_64 \
	libwfdrtsp_so_64 \
	libwfdservice_so_64 \
	libwfdsm_so_64 \
	libwfduibcinterface_so_64 \
	libwfduibcsink_so_64 \
	libwfduibcsinkinterface_so_64 \
	libwfduibcsrc_so_64 \
	libwfduibcsrcinterface_so_64 \
	libwms_so_64 \
	libwqe_so_64 \
	libxml_so_64 \
	libxt_native_so_64 \
	libxtadapter_so_64 \
	libxtwifi_ulp_adaptor_so_64 \
	libdrmclearkeyplugin_so_64 \
	sensors_ssc_so_64 \
	QtiTelephonyService \
	TimeService \
	datastatusnotification \
	shutdownlistener \
	MTP_Bluetooth_cal \
	MTP_General_cal \
	MTP_Global_cal \
	MTP_Handset_cal \
	MTP_Hdmi_cal \
	MTP_Headset_cal \
	MTP_Speaker_cal \
	Sony_Bluetooth_cal \
	Sony_General_cal \
	Sony_Global_cal \
	Sony_Handset_cal \
	Sony_Hdmi_cal \
	Sony_Headset_cal \
	Sony_Speaker_cal \
	ad_calib \
	SwimConfig \
	andsfCne \
	ATT_profile1 \
	ATT_profile2 \
	ATT_profile3 \
	ATT_profile4 \
	ROW_profile1 \
	ROW_profile2 \
	ROW_profile3 \
	ROW_profile4 \
	ROW_profile5 \
	VZW_profile1 \
	VZW_profile2 \
	VZW_profile3 \
	VZW_profile4 \
	VZW_profile5 \
	VZW_profile6 \
	NsrmConfiguration \
	a225_pfp \
	a225_pm4 \
	a225p5_pm4 \
	a300_pfp \
	a300_pm4 \
	a330_pfp \
	a330_pm4 \
	a420_pfp \
	a420_pm4 \
	cmnlib_b00 \
	cmnlib_b01 \
	cmnlib_b02 \
	cmnlib_b03 \
	cmnlib_mdt \
	cpp_firmware_v1_1_1 \
	cpp_firmware_v1_1_6 \
	cpp_firmware_v1_2_0 \
	cpp_firmware_v1_4_0 \
	cpp_firmware_v1_6_0 \
	cpp_firmware_v1_8_0 \
	fidocrypto_b00 \
	fidocrypto_b01 \
	fidocrypto_b02 \
	fidocrypto_b03 \
	fidocrypto_mdt \
	leia_pfp_470 \
	leia_pm4_470 \
	touch_module_id_0x01 \
	touch_module_id_0x02 \
	touch_module_id_0x03 \
	touch_module_id_0x04 \
	touch_module_id_0x05 \
	touch_module_id_0x06 \
	touch_module_id_0x07 \
	touch_module_id_0x08 \
	touch_module_id_0x1a \
	touch_module_id_0x1b \
	touch_module_id_0x1c \
	touch_module_id_0x1d \
	touch_module_id_0x1e \
	touch_module_id_0x1f \
	touch_module_id_0x20 \
	touch_module_id_0x21 \
	touch_module_id_0x22 \
	touch_module_id_0x23 \
	touch_module_id_0x26 \
	touch_module_id_0x27 \
	touch_module_id_0x2a \
	touch_module_id_0x2b \
	touch_module_id_0xa0 \
	touch_module_id_0xa1 \
	tzdtcpkctl_b00 \
	tzdtcpkctl_b01 \
	tzdtcpkctl_b02 \
	tzdtcpkctl_b03 \
	tzdtcpkctl_mdt \
	tzhdcp_b00 \
	tzhdcp_b01 \
	tzhdcp_b02 \
	tzhdcp_b03 \
	tzhdcp_mdt \
	tzlibasb_b00 \
	tzlibasb_b01 \
	tzlibasb_b02 \
	tzlibasb_b03 \
	tzlibasb_mdt \
	tznautilus_b00 \
	tznautilus_b01 \
	tznautilus_b02 \
	tznautilus_b03 \
	tznautilus_mdt \
	tzsuntory_b00 \
	tzsuntory_b01 \
	tzsuntory_b02 \
	tzsuntory_b03 \
	tzsuntory_mdt \
	tztpm_b00 \
	tztpm_b01 \
	tztpm_b02 \
	tztpm_b03 \
	tztpm_mdt \
	tzwidevine_b00 \
	tzwidevine_b01 \
	tzwidevine_b02 \
	tzwidevine_b03 \
	tzwidevine_mdt \
	tzwvcpybuf_b00 \
	tzwvcpybuf_b01 \
	tzwvcpybuf_b02 \
	tzwvcpybuf_b03 \
	tzwvcpybuf_mdt \
	venus_b00 \
	venus_b01 \
	venus_b02 \
	venus_b03 \
	venus_b04 \
	venus_mbn \
	venus_mdt \
	flashled_calc_parameters \
	iddd_conf \
	ConnectivityExt_xml \
	cneapiclient_xml \
	com_qti_dpmframework_xml \
	com_qti_location_sdk_xml \
	com_qti_snapdragon_sdk_display_xml \
	com_qualcomm_location_vzw_library_xml \
	com_qualcomm_location_xml \
	com_quicinc_cne_xml \
	dpmapi_xml \
	imscm \
	izat_xt_srv_xml \
	qcnvitems_xml \
	qcrilhook_xml \
	qti-vzw-ims-internal \
	qti_permissions \
	telephonyservice \
	hals \
	sensor_def_qcomdev \
	ConnectivityExt_jar \
	QtiTelephonyServicelibrary \
	cneapiclient_jar \
	com_qti_dpmframework_jar \
	com_qti_location_sdk_jar \
	com_qti_snapdragon_sdk_display_jar \
	com_qualcomm_location_vzw_library_jar \
	com_quicinc_cne_jar \
	dpmapi_jar \
	embmslibrary \
	imscmlibrary \
	izat_xt_srv_jar \
	qcnvitems_jar \
	qcrilhook_jar \
	qti-telephony-common \
	rcsimssettings \
	tcmclient \
	CNEService \
	com_qualcomm_location_apk \
	qcrilmsgtunnel \
	LKCore \
	adsprpcd \
	apfd \
	chamomile_provision \
	cnd \
	cnss-daemon \
	cnss_diag \
	display_color_calib \
	dpmd \
	garden_app \
	idd-logreader \
	iddd \
	illumination_service \
	ims_rtp_daemon \
	imscmservice \
	imsdatadaemon \
	imsqmidaemon \
	ipacm-diag \
	irsc_util \
	keyprovd \
	loc_launcher \
	lowi-server \
	mlog_qmi_service \
	mm-pp-daemon \
	mm-qcamera-daemon \
	msm_irqbalance \
	netmgrd \
	perfd \
	pm-proxy \
	pm-service \
	post_dumper \
	qmuxd \
	qseecomd \
	qti \
	rmt_storage \
	sct_service \
	secd \
	sensors \
	slim_daemon \
	startup-prober \
	ta_qmi_service \
	tad_static \
	taimport \
	tftp_server \
	thermal-engine \
	time_daemon \
	updatemiscta \
	xtwifi-client \
	xtwifi-inet-agent \
	tzfingerprint_b00 \
	tzfingerprint_b01 \
	tzfingerprint_b02 \
	tzfingerprint_b03 \
	tzfingerprint_mdt \
	LGI05BN0_color_ctrl_dat \
	LGI05BN0_dataflow_dat \
	LGI05BN0_debug_mgr_dat \
	LGI05BN0_exposure_ctrl_dat \
	LGI05BN0_exposure_ctrl_diagram_dat \
	LGI05BN0_exposure_ctrl_gamma_dat \
	LGI05BN0_face_detector_dat \
	LGI05BN0_flicker_detector_dat \
	LGI05BN0_focus_stats_conv_dat \
	LGI05BN0_food_comp_yummy_dat \
	LGI05BN0_food_detector_dat \
	LGI05BN0_hal_ctrl_dat \
	LGI05BN0_hal_ctrl_platform_dat \
	LGI05BN0_hal_ctrl_platform_abf_dat \
	LGI05BN0_hal_ctrl_platform_asf_lin_dat \
	LGI05BN0_hal_ctrl_platform_asf_stp_dat \
	LGI05BN0_hal_ctrl_platform_gic_dat \
	LGI05BN0_hdr_comp_dat \
	LGI05BN0_idt_ctrl_dat \
	LGI05BN0_image_conv_dat \
	LGI05BN0_image_conv_canele_dat \
	LGI05BN0_image_conv_marble_dat \
	LGI05BN0_image_conv_raisin_dat \
	LGI05BN0_image_conv_spica_dat \
	LGI05BN0_jpeg_enc_dat \
	LGI05BN0_lens_ctrl_dat \
	LGI05BN0_motion_estimation_dat \
	LGI05BN0_multiframe_nr_dat \
	LGI05BN0_multiframe_nr_melonpan_dat \
	LGI05BN0_multiframe_nr_mugichoco_dat \
	LGI05BN0_multiframe_nr_toppo_dat \
	LGI05BN0_object_tracker_dat \
	LGI05BN0_scene_detector_dat \
	LGI05BN0_snapshot_ctrl_dat \
	LGI05BN0_IMX241 \
	SEM05BN0_color_ctrl_dat \
	SEM05BN0_dataflow_dat \
	SEM05BN0_debug_mgr_dat \
	SEM05BN0_exposure_ctrl_dat \
	SEM05BN0_exposure_ctrl_diagram_dat \
	SEM05BN0_exposure_ctrl_gamma_dat \
	SEM05BN0_face_detector_dat \
	SEM05BN0_flicker_detector_dat \
	SEM05BN0_focus_stats_conv_dat \
	SEM05BN0_food_comp_yummy_dat \
	SEM05BN0_food_detector_dat \
	SEM05BN0_hal_ctrl_dat \
	SEM05BN0_hal_ctrl_platform_dat \
	SEM05BN0_hal_ctrl_platform_abf_dat \
	SEM05BN0_hal_ctrl_platform_asf_lin_dat \
	SEM05BN0_hal_ctrl_platform_asf_stp_dat \
	SEM05BN0_hal_ctrl_platform_gic_dat \
	SEM05BN0_hdr_comp_dat \
	SEM05BN0_idt_ctrl_dat \
	SEM05BN0_image_conv_dat \
	SEM05BN0_image_conv_canele_dat \
	SEM05BN0_image_conv_marble_dat \
	SEM05BN0_image_conv_raisin_dat \
	SEM05BN0_image_conv_spica_dat \
	SEM05BN0_jpeg_enc_dat \
	SEM05BN0_lens_ctrl_dat \
	SEM05BN0_motion_estimation_dat \
	SEM05BN0_multiframe_nr_dat \
	SEM05BN0_multiframe_nr_melonpan_dat \
	SEM05BN0_multiframe_nr_mugichoco_dat \
	SEM05BN0_multiframe_nr_toppo_dat \
	SEM05BN0_object_tracker_dat \
	SEM05BN0_scene_detector_dat \
	SEM05BN0_snapshot_ctrl_dat \
	SEM05BN0_IMX241 \
	SOI25BS0_color_ctrl_dat \
	SOI25BS0_dataflow_dat \
	SOI25BS0_debug_mgr_dat \
	SOI25BS0_exposure_ctrl_dat \
	SOI25BS0_exposure_ctrl_diagram_dat \
	SOI25BS0_exposure_ctrl_gamma_dat \
	SOI25BS0_face_detector_dat \
	SOI25BS0_flicker_detector_dat \
	SOI25BS0_focus_stats_conv_dat \
	SOI25BS0_food_comp_yummy_dat \
	SOI25BS0_food_detector_dat \
	SOI25BS0_hal_ctrl_dat \
	SOI25BS0_hal_ctrl_platform_dat \
	SOI25BS0_hal_ctrl_platform_abf_dat \
	SOI25BS0_hal_ctrl_platform_asf_lin_dat \
	SOI25BS0_hal_ctrl_platform_asf_stp_dat \
	SOI25BS0_hal_ctrl_platform_gic_dat \
	SOI25BS0_hdr_comp_dat \
	SOI25BS0_idt_ctrl_dat \
	SOI25BS0_image_conv_dat \
	SOI25BS0_image_conv_canele_dat \
	SOI25BS0_image_conv_marble_dat \
	SOI25BS0_image_conv_raisin_dat \
	SOI25BS0_image_conv_spica_dat \
	SOI25BS0_jpeg_enc_dat \
	SOI25BS0_lens_ctrl_dat \
	SOI25BS0_motion_estimation_dat \
	SOI25BS0_multiframe_nr_dat \
	SOI25BS0_multiframe_nr_melonpan_dat \
	SOI25BS0_multiframe_nr_mugichoco_dat \
	SOI25BS0_multiframe_nr_toppo_dat \
	SOI25BS0_object_tracker_dat \
	SOI25BS0_scene_detector_dat \
	SOI25BS0_snapshot_ctrl_dat \
	SOI25BS0_BU64747GWZ \
	SOI25BS0_BU64747GWZ_XCF \
	SOI25BS0_BU64747GWZ_XFW \
	SOI25BS0_IMX300 \
	SOI25BS1_color_ctrl_dat \
	SOI25BS1_dataflow_dat \
	SOI25BS1_debug_mgr_dat \
	SOI25BS1_exposure_ctrl_dat \
	SOI25BS1_exposure_ctrl_diagram_dat \
	SOI25BS1_exposure_ctrl_gamma_dat \
	SOI25BS1_face_detector_dat \
	SOI25BS1_flicker_detector_dat \
	SOI25BS1_focus_stats_conv_dat \
	SOI25BS1_food_comp_yummy_dat \
	SOI25BS1_food_detector_dat \
	SOI25BS1_hal_ctrl_dat \
	SOI25BS1_hal_ctrl_platform_dat \
	SOI25BS1_hal_ctrl_platform_abf_dat \
	SOI25BS1_hal_ctrl_platform_asf_lin_dat \
	SOI25BS1_hal_ctrl_platform_asf_stp_dat \
	SOI25BS1_hal_ctrl_platform_gic_dat \
	SOI25BS1_hdr_comp_dat \
	SOI25BS1_idt_ctrl_dat \
	SOI25BS1_image_conv_dat \
	SOI25BS1_image_conv_canele_dat \
	SOI25BS1_image_conv_marble_dat \
	SOI25BS1_image_conv_raisin_dat \
	SOI25BS1_image_conv_spica_dat \
	SOI25BS1_jpeg_enc_dat \
	SOI25BS1_lens_ctrl_dat \
	SOI25BS1_motion_estimation_dat \
	SOI25BS1_multiframe_nr_dat \
	SOI25BS1_multiframe_nr_melonpan_dat \
	SOI25BS1_multiframe_nr_mugichoco_dat \
	SOI25BS1_multiframe_nr_toppo_dat \
	SOI25BS1_object_tracker_dat \
	SOI25BS1_scene_detector_dat \
	SOI25BS1_snapshot_ctrl_dat \
	SOI25BS1_BU64747GWZ \
	SOI25BS1_BU64747GWZ_XCF \
	SOI25BS1_BU64747GWZ_XFW \
	SOI25BS1_IMX300 \
	SOI25BS2_color_ctrl_dat \
	SOI25BS2_dataflow_dat \
	SOI25BS2_debug_mgr_dat \
	SOI25BS2_exposure_ctrl_dat \
	SOI25BS2_exposure_ctrl_diagram_dat \
	SOI25BS2_exposure_ctrl_gamma_dat \
	SOI25BS2_face_detector_dat \
	SOI25BS2_flicker_detector_dat \
	SOI25BS2_focus_stats_conv_dat \
	SOI25BS2_food_comp_yummy_dat \
	SOI25BS2_food_detector_dat \
	SOI25BS2_hal_ctrl_dat \
	SOI25BS2_hal_ctrl_platform_dat \
	SOI25BS2_hal_ctrl_platform_abf_dat \
	SOI25BS2_hal_ctrl_platform_asf_lin_dat \
	SOI25BS2_hal_ctrl_platform_asf_stp_dat \
	SOI25BS2_hal_ctrl_platform_gic_dat \
	SOI25BS2_hdr_comp_dat \
	SOI25BS2_idt_ctrl_dat \
	SOI25BS2_image_conv_dat \
	SOI25BS2_image_conv_canele_dat \
	SOI25BS2_image_conv_marble_dat \
	SOI25BS2_image_conv_raisin_dat \
	SOI25BS2_image_conv_spica_dat \
	SOI25BS2_jpeg_enc_dat \
	SOI25BS2_lens_ctrl_dat \
	SOI25BS2_motion_estimation_dat \
	SOI25BS2_multiframe_nr_dat \
	SOI25BS2_multiframe_nr_melonpan_dat \
	SOI25BS2_multiframe_nr_mugichoco_dat \
	SOI25BS2_multiframe_nr_toppo_dat \
	SOI25BS2_object_tracker_dat \
	SOI25BS2_scene_detector_dat \
	SOI25BS2_snapshot_ctrl_dat \
	SOI25BS2_BU64747GWZ \
	SOI25BS2_BU64747GWZ_XCF \
	SOI25BS2_BU64747GWZ_XFW \
	SOI25BS2_IMX300 \
	SOI25BS3_color_ctrl_dat \
	SOI25BS3_dataflow_dat \
	SOI25BS3_debug_mgr_dat \
	SOI25BS3_exposure_ctrl_dat \
	SOI25BS3_exposure_ctrl_diagram_dat \
	SOI25BS3_exposure_ctrl_gamma_dat \
	SOI25BS3_face_detector_dat \
	SOI25BS3_flicker_detector_dat \
	SOI25BS3_focus_stats_conv_dat \
	SOI25BS3_food_comp_yummy_dat \
	SOI25BS3_food_detector_dat \
	SOI25BS3_hal_ctrl_dat \
	SOI25BS3_hal_ctrl_platform_dat \
	SOI25BS3_hal_ctrl_platform_abf_dat \
	SOI25BS3_hal_ctrl_platform_asf_lin_dat \
	SOI25BS3_hal_ctrl_platform_asf_stp_dat \
	SOI25BS3_hal_ctrl_platform_gic_dat \
	SOI25BS3_hdr_comp_dat \
	SOI25BS3_idt_ctrl_dat \
	SOI25BS3_image_conv_dat \
	SOI25BS3_image_conv_canele_dat \
	SOI25BS3_image_conv_marble_dat \
	SOI25BS3_image_conv_raisin_dat \
	SOI25BS3_image_conv_spica_dat \
	SOI25BS3_jpeg_enc_dat \
	SOI25BS3_lens_ctrl_dat \
	SOI25BS3_motion_estimation_dat \
	SOI25BS3_multiframe_nr_dat \
	SOI25BS3_multiframe_nr_melonpan_dat \
	SOI25BS3_multiframe_nr_mugichoco_dat \
	SOI25BS3_multiframe_nr_toppo_dat \
	SOI25BS3_object_tracker_dat \
	SOI25BS3_scene_detector_dat \
	SOI25BS3_snapshot_ctrl_dat \
	SOI25BS3_BU64747GWZ \
	SOI25BS3_BU64747GWZ_XCF \
	SOI25BS3_BU64747GWZ_XFW \
	SOI25BS3_IMX300 \
	SOI25BS4_color_ctrl_dat \
	SOI25BS4_dataflow_dat \
	SOI25BS4_debug_mgr_dat \
	SOI25BS4_exposure_ctrl_dat \
	SOI25BS4_exposure_ctrl_diagram_dat \
	SOI25BS4_exposure_ctrl_gamma_dat \
	SOI25BS4_face_detector_dat \
	SOI25BS4_flicker_detector_dat \
	SOI25BS4_focus_stats_conv_dat \
	SOI25BS4_food_comp_yummy_dat \
	SOI25BS4_food_detector_dat \
	SOI25BS4_hal_ctrl_dat \
	SOI25BS4_hal_ctrl_platform_dat \
	SOI25BS4_hal_ctrl_platform_abf_dat \
	SOI25BS4_hal_ctrl_platform_asf_lin_dat \
	SOI25BS4_hal_ctrl_platform_asf_stp_dat \
	SOI25BS4_hal_ctrl_platform_gic_dat \
	SOI25BS4_hdr_comp_dat \
	SOI25BS4_idt_ctrl_dat \
	SOI25BS4_image_conv_dat \
	SOI25BS4_image_conv_canele_dat \
	SOI25BS4_image_conv_marble_dat \
	SOI25BS4_image_conv_raisin_dat \
	SOI25BS4_image_conv_spica_dat \
	SOI25BS4_jpeg_enc_dat \
	SOI25BS4_lens_ctrl_dat \
	SOI25BS4_motion_estimation_dat \
	SOI25BS4_multiframe_nr_dat \
	SOI25BS4_multiframe_nr_melonpan_dat \
	SOI25BS4_multiframe_nr_mugichoco_dat \
	SOI25BS4_multiframe_nr_toppo_dat \
	SOI25BS4_object_tracker_dat \
	SOI25BS4_scene_detector_dat \
	SOI25BS4_snapshot_ctrl_dat \
	SOI25BS4_BU64747GWZ \
	SOI25BS4_BU64747GWZ_XCF \
	SOI25BS4_BU64747GWZ_XFW \
	SOI25BS4_IMX300 \
	default \
	flash \
	snapshot \
	streaming \
	supported \
	version
