# Copyright (C) 2014 The OmniROM Project
#
# Xperia L proprietary blob list.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/taoshan/setup-makefiles.sh


PRODUCT_COPY_FILES += \
    vendor/sony/taoshan/proprietary/bin/akmd8963:system/bin/akmd8963 \
    vendor/sony/taoshan/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/sony/taoshan/proprietary/bin/e2fsck:system/bin/e2fsck \
    vendor/sony/taoshan/proprietary/bin/efsks:system/bin/efsks \
    vendor/sony/taoshan/proprietary/bin/gpsone_daemon:system/bin/gpsone_daemon \
    vendor/sony/taoshan/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/sony/taoshan/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/sony/taoshan/proprietary/bin/ks:system/bin/ks \
    vendor/sony/taoshan/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/sony/taoshan/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/sony/taoshan/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/sony/taoshan/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/sony/taoshan/proprietary/bin/qcks:system/bin/qcks \
    vendor/sony/taoshan/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/sony/taoshan/proprietary/bin/qrngd:system/bin/qrngd \
    vendor/sony/taoshan/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/sony/taoshan/proprietary/bin/rild:system/bin/rild \
    vendor/sony/taoshan/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/sony/taoshan/proprietary/bin/taimport:system/bin/taimport \
    vendor/sony/taoshan/proprietary/bin/ta_qmi_service:system/bin/ta_qmi_service \
    vendor/sony/taoshan/proprietary/bin/thermald:system/bin/thermald \
    vendor/sony/taoshan/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/sony/taoshan/proprietary/bin/updatemiscta:system/bin/updatemiscta \
    vendor/sony/taoshan/proprietary/bin/xtwifi-client:system/bin/xtwifi-client \
    vendor/sony/taoshan/proprietary/bin/xtwifi-inet-agent:system/bin/xtwifi-inet-agent \
    vendor/sony/taoshan/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/sony/taoshan/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/sony/taoshan/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/sony/taoshan/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/sony/taoshan/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/sony/taoshan/proprietary/etc/firmware/cyttsp_8064_mtp.hex:system/etc/firmware/cyttsp_8064_mtp.hex \
    vendor/sony/taoshan/proprietary/etc/firmware/cyttsp_8960_cdp.hex:system/etc/firmware/cyttsp_8960_cdp.hex \
    vendor/sony/taoshan/proprietary/etc/firmware/dxhdcp2.b00:system/etc/firmware/dxhdcp2.b00 \
    vendor/sony/taoshan/proprietary/etc/firmware/dxhdcp2.b01:system/etc/firmware/dxhdcp2.b01 \
    vendor/sony/taoshan/proprietary/etc/firmware/dxhdcp2.b02:system/etc/firmware/dxhdcp2.b02 \
    vendor/sony/taoshan/proprietary/etc/firmware/dxhdcp2.b03:system/etc/firmware/dxhdcp2.b03 \
    vendor/sony/taoshan/proprietary/etc/firmware/dxhdcp2.mdt:system/etc/firmware/dxhdcp2.mdt \
    vendor/sony/taoshan/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/sony/taoshan/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/sony/taoshan/proprietary/etc/firmware/libpn544_fw.so:system/etc/firmware/libpn544_fw.so \
    vendor/sony/taoshan/proprietary/etc/firmware/tzlibasb.b00:system/etc/firmware/tzlibasb.b00 \
    vendor/sony/taoshan/proprietary/etc/firmware/tzlibasb.b01:system/etc/firmware/tzlibasb.b01 \
    vendor/sony/taoshan/proprietary/etc/firmware/tzlibasb.b02:system/etc/firmware/tzlibasb.b02 \
    vendor/sony/taoshan/proprietary/etc/firmware/tzlibasb.b03:system/etc/firmware/tzlibasb.b03 \
    vendor/sony/taoshan/proprietary/etc/firmware/tzlibasb.mdt:system/etc/firmware/tzlibasb.mdt \
    vendor/sony/taoshan/proprietary/etc/firmware/tzsuntory.b00:system/etc/firmware/tzsuntory.b00 \
    vendor/sony/taoshan/proprietary/etc/firmware/tzsuntory.b01:system/etc/firmware/tzsuntory.b01 \
    vendor/sony/taoshan/proprietary/etc/firmware/tzsuntory.b02:system/etc/firmware/tzsuntory.b02 \
    vendor/sony/taoshan/proprietary/etc/firmware/tzsuntory.b03:system/etc/firmware/tzsuntory.b03 \
    vendor/sony/taoshan/proprietary/etc/firmware/tzsuntory.mdt:system/etc/firmware/tzsuntory.mdt \
    vendor/sony/taoshan/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/sony/taoshan/proprietary/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
    vendor/sony/taoshan/proprietary/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
    vendor/sony/taoshan/proprietary/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
    vendor/sony/taoshan/proprietary/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
    vendor/sony/taoshan/proprietary/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf \
    vendor/sony/taoshan/proprietary/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
    vendor/sony/taoshan/proprietary/etc/firmware/wlan/prima/WCNSS_cfg.dat:system/etc/firmware/wlan/prima/WCNSS_cfg.dat \
    vendor/sony/taoshan/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin:system/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin \
    vendor/sony/taoshan/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/sony/taoshan/proprietary/lib/hw/nfc.default.so:system/lib/hw/nfc.default.so \
    vendor/sony/taoshan/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/sony/taoshan/proprietary/lib/hw/vendor-camera.qcom.so:system/lib/hw/vendor-camera.qcom.so \
    vendor/sony/taoshan/proprietary/lib/hw/vendor-lights.default.so:system/lib/hw/vendor-lights.default.so \
    vendor/sony/taoshan/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/sony/taoshan/proprietary/lib/libadsprpc.so:system/lib/libadsprpc.so \
    vendor/sony/taoshan/proprietary/lib/libalsa-intf.so:system/lib/libalsa-intf.so \
    vendor/sony/taoshan/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/sony/taoshan/proprietary/lib/libc2d2_a3xx.so:system/lib/libc2d2_a3xx.so \
    vendor/sony/taoshan/proprietary/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
    vendor/sony/taoshan/proprietary/lib/libchromatix_imx134_default_video.so:system/lib/libchromatix_imx134_default_video.so \
    vendor/sony/taoshan/proprietary/lib/libchromatix_imx134_hfr_120fps.so:system/lib/libchromatix_imx134_hfr_120fps.so \
    vendor/sony/taoshan/proprietary/lib/libchromatix_imx134_hfr_60fps.so:system/lib/libchromatix_imx134_hfr_60fps.so \
    vendor/sony/taoshan/proprietary/lib/libchromatix_imx134_preview.so:system/lib/libchromatix_imx134_preview.so \
    vendor/sony/taoshan/proprietary/lib/libchromatix_imx134_video_hd.so:system/lib/libchromatix_imx134_video_hd.so \
    vendor/sony/taoshan/proprietary/lib/libchromatix_imx134_video_hdr.so:system/lib/libchromatix_imx134_video_hdr.so \
    vendor/sony/taoshan/proprietary/lib/libchromatix_imx134_zsl.so:system/lib/libchromatix_imx134_zsl.so \
    vendor/sony/taoshan/proprietary/lib/libcsd-client.so:system/lib/libcsd-client.so \
    vendor/sony/taoshan/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/sony/taoshan/proprietary/lib/libdrmdiag.so:system/lib/libdrmdiag.so \
    vendor/sony/taoshan/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/sony/taoshan/proprietary/lib/libdrmtime.so:system/lib/libdrmtime.so \
    vendor/sony/taoshan/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/sony/taoshan/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/sony/taoshan/proprietary/lib/libfastcvopt.so:system/lib/libfastcvopt.so \
    vendor/sony/taoshan/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/sony/taoshan/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/sony/taoshan/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/sony/taoshan/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/sony/taoshan/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/sony/taoshan/proprietary/lib/liblights-core.so:system/lib/liblights-core.so \
    vendor/sony/taoshan/proprietary/lib/libllvm-a3xx.so:system/lib/libllvm-a3xx.so \
    vendor/sony/taoshan/proprietary/lib/libmercury.so:system/lib/libmercury.so \
    vendor/sony/taoshan/proprietary/lib/libmiscta.so:system/lib/libmiscta.so \
    vendor/sony/taoshan/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
    vendor/sony/taoshan/proprietary/lib/libmm-audio-resampler.so:system/lib/libmm-audio-resampler.so \
    vendor/sony/taoshan/proprietary/lib/libmmcamera_3a_legacy.so:system/lib/libmmcamera_3a_legacy.so \
    vendor/sony/taoshan/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/sony/taoshan/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/sony/taoshan/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/sony/taoshan/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/sony/taoshan/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/sony/taoshan/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/sony/taoshan/proprietary/lib/libmmcamera_plugin.so:system/lib/libmmcamera_plugin.so \
    vendor/sony/taoshan/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/sony/taoshan/proprietary/lib/libmmcamera_tintless_algo.so:system/lib/libmmcamera_tintless_algo.so \
    vendor/sony/taoshan/proprietary/lib/libmmcamera_tintless_wrapper.so:system/lib/libmmcamera_tintless_wrapper.so \
    vendor/sony/taoshan/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/sony/taoshan/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/sony/taoshan/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/sony/taoshan/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/sony/taoshan/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/sony/taoshan/proprietary/lib/libmorpho_denoiser.so:system/lib/libmorpho_denoiser.so \
    vendor/sony/taoshan/proprietary/lib/libmorpho_easy_hdr.so:system/lib/libmorpho_easy_hdr.so \
    vendor/sony/taoshan/proprietary/lib/libmorpho_edit_engine.so:system/lib/libmorpho_edit_engine.so \
    vendor/sony/taoshan/proprietary/lib/libmorpho_fdw.so:system/lib/libmorpho_fdw.so \
    vendor/sony/taoshan/proprietary/lib/libmorpho_hdr_checker.so:system/lib/libmorpho_hdr_checker.so \
    vendor/sony/taoshan/proprietary/lib/libmorpho_image_stabilizer3.so:system/lib/libmorpho_image_stabilizer3.so \
    vendor/sony/taoshan/proprietary/lib/libmorpho_posture_detect.so:system/lib/libmorpho_posture_detect.so \
    vendor/sony/taoshan/proprietary/lib/libmorpho_scene_detector.so:system/lib/libmorpho_scene_detector.so \
    vendor/sony/taoshan/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/sony/taoshan/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/sony/taoshan/proprietary/lib/libprofiler_msmadc.so:system/lib/libprofiler_msmadc.so \
    vendor/sony/taoshan/proprietary/lib/libqcci_adc.so:system/lib/libqcci_adc.so \
    vendor/sony/taoshan/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
    vendor/sony/taoshan/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/sony/taoshan/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/sony/taoshan/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/sony/taoshan/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
    vendor/sony/taoshan/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/sony/taoshan/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
    vendor/sony/taoshan/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
    vendor/sony/taoshan/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
    vendor/sony/taoshan/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/sony/taoshan/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/sony/taoshan/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/sony/taoshan/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/sony/taoshan/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/sony/taoshan/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/sony/taoshan/proprietary/lib/libsc-a3xx.so:system/lib/libsc-a3xx.so \
    vendor/sony/taoshan/proprietary/lib/libsensor1.so:system/lib/libsensor1.so \
    vendor/sony/taoshan/proprietary/lib/libsensor_reg.so:system/lib/libsensor_reg.so \
    vendor/sony/taoshan/proprietary/lib/libsurround_proc.so:system/lib/libsurround_proc.so \
    vendor/sony/taoshan/proprietary/lib/libta.so:system/lib/libta.so \
    vendor/sony/taoshan/proprietary/lib/libtime_genoff.so:system/lib/libtime_genoff.so \
    vendor/sony/taoshan/proprietary/lib/libtzplayready.so:system/lib/libtzplayready.so
