# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/kugo/setup-makefiles.sh

PRODUCT_PLATFORM := loire

$(call inherit-product, vendor/sony/loire-common-caf/loire-vendor.mk)

PRODUCT_COPY_FILES += \
    vendor/sony/loire-kugo-caf/proprietary/etc/firmware/touch_module_id_0xa0.img:system/etc/firmware/touch_module_id_0xa0.img \
    vendor/sony/loire-kugo-caf/proprietary/etc/firmware/touch_module_id_0xa1.img:system/etc/firmware/touch_module_id_0xa1.img \
    vendor/sony/loire-kugo-caf/proprietary/etc/firmware/touch_module_id_0xa2.img:system/etc/firmware/touch_module_id_0xa2.img \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/color_ctrl.dat:system/vendor/camera/LGI05BN0/color_ctrl.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/dataflow.dat:system/vendor/camera/LGI05BN0/dataflow.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/exposure_ctrl.dat:system/vendor/camera/LGI05BN0/exposure_ctrl.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/exposure_ctrl_diagram.dat:system/vendor/camera/LGI05BN0/exposure_ctrl_diagram.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/exposure_ctrl_gamma.dat:system/vendor/camera/LGI05BN0/exposure_ctrl_gamma.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/face_detector.dat:system/vendor/camera/LGI05BN0/face_detector.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/flicker_detector.dat:system/vendor/camera/LGI05BN0/flicker_detector.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/focus_stats_conv.dat:system/vendor/camera/LGI05BN0/focus_stats_conv.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/food_comp_yummy.dat:system/vendor/camera/LGI05BN0/food_comp_yummy.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/food_detector.dat:system/vendor/camera/LGI05BN0/food_detector.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/hal_ctrl.dat:system/vendor/camera/LGI05BN0/hal_ctrl.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/hal_ctrl_platform.dat:system/vendor/camera/LGI05BN0/hal_ctrl_platform.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/hal_ctrl_platform_abf.dat:system/vendor/camera/LGI05BN0/hal_ctrl_platform_abf.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/hal_ctrl_platform_asf_lin.dat:system/vendor/camera/LGI05BN0/hal_ctrl_platform_asf_lin.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/hal_ctrl_platform_asf_stp.dat:system/vendor/camera/LGI05BN0/hal_ctrl_platform_asf_stp.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/hal_ctrl_platform_ltm.dat:system/vendor/camera/LGI05BN0/hal_ctrl_platform_ltm.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/hdr_comp.dat:system/vendor/camera/LGI05BN0/hdr_comp.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/idt_ctrl.dat:system/vendor/camera/LGI05BN0/idt_ctrl.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/image_conv.dat:system/vendor/camera/LGI05BN0/image_conv.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/image_conv_canele.dat:system/vendor/camera/LGI05BN0/image_conv_canele.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/image_conv_cheesescone.dat:system/vendor/camera/LGI05BN0/image_conv_cheesescone.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/image_conv_dars.dat:system/vendor/camera/LGI05BN0/image_conv_dars.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/image_conv_marble.dat:system/vendor/camera/LGI05BN0/image_conv_marble.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/image_conv_raisin.dat:system/vendor/camera/LGI05BN0/image_conv_raisin.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/image_conv_spica.dat:system/vendor/camera/LGI05BN0/image_conv_spica.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/lens_ctrl.dat:system/vendor/camera/LGI05BN0/lens_ctrl.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/motion_detector.dat:system/vendor/camera/LGI05BN0/motion_detector.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/motion_detector_sumomo.dat:system/vendor/camera/LGI05BN0/motion_detector_sumomo.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/motion_estimation.dat:system/vendor/camera/LGI05BN0/motion_estimation.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/multiframe_nr.dat:system/vendor/camera/LGI05BN0/multiframe_nr.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/multiframe_nr_melonpan.dat:system/vendor/camera/LGI05BN0/multiframe_nr_melonpan.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/multiframe_nr_mugichoco.dat:system/vendor/camera/LGI05BN0/multiframe_nr_mugichoco.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/multiframe_nr_toppo.dat:system/vendor/camera/LGI05BN0/multiframe_nr_toppo.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/object_tracker.dat:system/vendor/camera/LGI05BN0/object_tracker.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/prc_image_conv.dat:system/vendor/camera/LGI05BN0/prc_image_conv.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/LGI05BN0/scene_detector.dat:system/vendor/camera/LGI05BN0/scene_detector.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/color_ctrl.dat:system/vendor/camera/SEM05BN0/color_ctrl.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/dataflow.dat:system/vendor/camera/SEM05BN0/dataflow.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/exposure_ctrl.dat:system/vendor/camera/SEM05BN0/exposure_ctrl.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/exposure_ctrl_diagram.dat:system/vendor/camera/SEM05BN0/exposure_ctrl_diagram.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/exposure_ctrl_gamma.dat:system/vendor/camera/SEM05BN0/exposure_ctrl_gamma.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/face_detector.dat:system/vendor/camera/SEM05BN0/face_detector.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/flicker_detector.dat:system/vendor/camera/SEM05BN0/flicker_detector.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/focus_stats_conv.dat:system/vendor/camera/SEM05BN0/focus_stats_conv.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/food_comp_yummy.dat:system/vendor/camera/SEM05BN0/food_comp_yummy.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/food_detector.dat:system/vendor/camera/SEM05BN0/food_detector.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/hal_ctrl.dat:system/vendor/camera/SEM05BN0/hal_ctrl.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/hal_ctrl_platform.dat:system/vendor/camera/SEM05BN0/hal_ctrl_platform.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/hal_ctrl_platform_abf.dat:system/vendor/camera/SEM05BN0/hal_ctrl_platform_abf.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/hal_ctrl_platform_asf_lin.dat:system/vendor/camera/SEM05BN0/hal_ctrl_platform_asf_lin.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/hal_ctrl_platform_asf_stp.dat:system/vendor/camera/SEM05BN0/hal_ctrl_platform_asf_stp.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/hal_ctrl_platform_ltm.dat:system/vendor/camera/SEM05BN0/hal_ctrl_platform_ltm.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/hdr_comp.dat:system/vendor/camera/SEM05BN0/hdr_comp.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/idt_ctrl.dat:system/vendor/camera/SEM05BN0/idt_ctrl.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/image_conv.dat:system/vendor/camera/SEM05BN0/image_conv.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/image_conv_canele.dat:system/vendor/camera/SEM05BN0/image_conv_canele.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/image_conv_cheesescone.dat:system/vendor/camera/SEM05BN0/image_conv_cheesescone.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/image_conv_dars.dat:system/vendor/camera/SEM05BN0/image_conv_dars.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/image_conv_marble.dat:system/vendor/camera/SEM05BN0/image_conv_marble.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/image_conv_raisin.dat:system/vendor/camera/SEM05BN0/image_conv_raisin.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/image_conv_spica.dat:system/vendor/camera/SEM05BN0/image_conv_spica.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/lens_ctrl.dat:system/vendor/camera/SEM05BN0/lens_ctrl.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/motion_detector.dat:system/vendor/camera/SEM05BN0/motion_detector.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/motion_detector_sumomo.dat:system/vendor/camera/SEM05BN0/motion_detector_sumomo.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/motion_estimation.dat:system/vendor/camera/SEM05BN0/motion_estimation.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/multiframe_nr.dat:system/vendor/camera/SEM05BN0/multiframe_nr.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/multiframe_nr_melonpan.dat:system/vendor/camera/SEM05BN0/multiframe_nr_melonpan.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/multiframe_nr_mugichoco.dat:system/vendor/camera/SEM05BN0/multiframe_nr_mugichoco.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/multiframe_nr_toppo.dat:system/vendor/camera/SEM05BN0/multiframe_nr_toppo.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/object_tracker.dat:system/vendor/camera/SEM05BN0/object_tracker.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/prc_image_conv.dat:system/vendor/camera/SEM05BN0/prc_image_conv.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SEM05BN0/scene_detector.dat:system/vendor/camera/SEM05BN0/scene_detector.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/color_ctrl.dat:system/vendor/camera/SOI25BS4/color_ctrl.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/dataflow.dat:system/vendor/camera/SOI25BS4/dataflow.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/exposure_ctrl.dat:system/vendor/camera/SOI25BS4/exposure_ctrl.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/exposure_ctrl_diagram.dat:system/vendor/camera/SOI25BS4/exposure_ctrl_diagram.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/exposure_ctrl_gamma.dat:system/vendor/camera/SOI25BS4/exposure_ctrl_gamma.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/face_detector.dat:system/vendor/camera/SOI25BS4/face_detector.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/flicker_detector.dat:system/vendor/camera/SOI25BS4/flicker_detector.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/focus_stats_conv.dat:system/vendor/camera/SOI25BS4/focus_stats_conv.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/food_comp_yummy.dat:system/vendor/camera/SOI25BS4/food_comp_yummy.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/food_detector.dat:system/vendor/camera/SOI25BS4/food_detector.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/hal_ctrl.dat:system/vendor/camera/SOI25BS4/hal_ctrl.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/hal_ctrl_platform.dat:system/vendor/camera/SOI25BS4/hal_ctrl_platform.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/hal_ctrl_platform_abf.dat:system/vendor/camera/SOI25BS4/hal_ctrl_platform_abf.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/hal_ctrl_platform_asf_lin.dat:system/vendor/camera/SOI25BS4/hal_ctrl_platform_asf_lin.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/hal_ctrl_platform_asf_stp.dat:system/vendor/camera/SOI25BS4/hal_ctrl_platform_asf_stp.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/hal_ctrl_platform_ltm.dat:system/vendor/camera/SOI25BS4/hal_ctrl_platform_ltm.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/hdr_comp.dat:system/vendor/camera/SOI25BS4/hdr_comp.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/idt_ctrl.dat:system/vendor/camera/SOI25BS4/idt_ctrl.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/image_conv.dat:system/vendor/camera/SOI25BS4/image_conv.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/image_conv_canele.dat:system/vendor/camera/SOI25BS4/image_conv_canele.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/image_conv_cheesescone.dat:system/vendor/camera/SOI25BS4/image_conv_cheesescone.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/image_conv_dars.dat:system/vendor/camera/SOI25BS4/image_conv_dars.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/image_conv_marble.dat:system/vendor/camera/SOI25BS4/image_conv_marble.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/image_conv_raisin.dat:system/vendor/camera/SOI25BS4/image_conv_raisin.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/image_conv_spica.dat:system/vendor/camera/SOI25BS4/image_conv_spica.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/lens_ctrl.dat:system/vendor/camera/SOI25BS4/lens_ctrl.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/motion_detector.dat:system/vendor/camera/SOI25BS4/motion_detector.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/motion_detector_sumomo.dat:system/vendor/camera/SOI25BS4/motion_detector_sumomo.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/motion_estimation.dat:system/vendor/camera/SOI25BS4/motion_estimation.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/multiframe_nr.dat:system/vendor/camera/SOI25BS4/multiframe_nr.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/multiframe_nr_melonpan.dat:system/vendor/camera/SOI25BS4/multiframe_nr_melonpan.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/multiframe_nr_mugichoco.dat:system/vendor/camera/SOI25BS4/multiframe_nr_mugichoco.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/multiframe_nr_toppo.dat:system/vendor/camera/SOI25BS4/multiframe_nr_toppo.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/object_tracker.dat:system/vendor/camera/SOI25BS4/object_tracker.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/prc_image_conv.dat:system/vendor/camera/SOI25BS4/prc_image_conv.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4/scene_detector.dat:system/vendor/camera/SOI25BS4/scene_detector.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4_BU64747GWZ.dat:system/vendor/camera/SOI25BS4_BU64747GWZ.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4_BU64747GWZ_XCF.dat:system/vendor/camera/SOI25BS4_BU64747GWZ_XCF.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/SOI25BS4_BU64747GWZ_XFW.dat:system/vendor/camera/SOI25BS4_BU64747GWZ_XFW.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/default.dat:system/vendor/camera/default.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/flash.dat:system/vendor/camera/flash.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/snapshot.dat:system/vendor/camera/snapshot.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/streaming.dat:system/vendor/camera/streaming.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/supported.dat:system/vendor/camera/supported.dat \
    vendor/sony/loire-kugo-caf/proprietary/vendor/camera/version.dat:system/vendor/camera/version.dat
