# Copyright (C) 2017 Sony Mobile Communication
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/loire/setup-makefiles.sh

PRODUCT_PLATFORM := loire

$(call inherit-product, vendor/sony/aosp_nxp/nxp-vendor.mk)
$(call inherit-product, vendor/sony/loire-common-caf/loire-partial.mk)

PRODUCT_COPY_FILES += \
    vendor/sony/loire-common-caf/proprietary/etc/ad_calib.cfg:system/etc/ad_calib.cfg \
    vendor/sony/loire-common-caf/proprietary/etc/cne/SwimConfig.xml:system/etc/cne/SwimConfig.xml \
    vendor/sony/loire-common-caf/proprietary/etc/cne/andsfCne.xml:system/etc/cne/andsfCne.xml \
    vendor/sony/loire-common-caf/proprietary/etc/dpm/dpm.conf:system/etc/dpm/dpm.conf \
    vendor/sony/loire-common-caf/proprietary/etc/dpm/nsrm/NsrmConfiguration.xml:system/etc/dpm/nsrm/NsrmConfiguration.xml \
    vendor/sony/loire-common-caf/proprietary/etc/flashled_calc_parameters.cfg:system/etc/flashled_calc_parameters.cfg \
    vendor/sony/loire-common-caf/proprietary/etc/iddd.conf:system/etc/iddd.conf \
    vendor/sony/loire-common-caf/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    vendor/sony/loire-common-caf/proprietary/etc/permissions/com.qti.location.sdk.xml:system/etc/permissions/com.qti.location.sdk.xml \
    vendor/sony/loire-common-caf/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    vendor/sony/loire-common-caf/proprietary/etc/permissions/com.quicinc.cne.xml:system/etc/permissions/com.quicinc.cne.xml \
    vendor/sony/loire-common-caf/proprietary/etc/permissions/imscm.xml:system/etc/permissions/imscm.xml \
    vendor/sony/loire-common-caf/proprietary/etc/permissions/izat.xt.srv.xml:system/etc/permissions/izat.xt.srv.xml \
    vendor/sony/loire-common-caf/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    vendor/sony/loire-common-caf/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/sony/loire-common-caf/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/sony/loire-common-caf/proprietary/framework/cneapiclient.jar:system/framework/cneapiclient.jar \
    vendor/sony/loire-common-caf/proprietary/framework/com.qti.location.sdk.jar:system/framework/com.qti.location.sdk.jar \
    vendor/sony/loire-common-caf/proprietary/framework/com.quicinc.cne.jar:system/framework/com.quicinc.cne.jar \
    vendor/sony/loire-common-caf/proprietary/framework/imscmlibrary.jar:system/framework/imscmlibrary.jar \
    vendor/sony/loire-common-caf/proprietary/framework/izat.xt.srv.jar:system/framework/izat.xt.srv.jar \
    vendor/sony/loire-common-caf/proprietary/framework/qcnvitems.jar:system/framework/qcnvitems.jar \
    vendor/sony/loire-common-caf/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/sony/loire-common-caf/proprietary/framework/rcsimssettings.jar:system/framework/rcsimssettings.jar \
    vendor/sony/loire-common-caf/proprietary/lib/libstagefright_soft_flacdec.so:system/lib/libstagefright_soft_flacdec.so \
    vendor/sony/loire-common-caf/proprietary/lib64/libloc_api_v02.so:system/lib64/libloc_api_v02.so \
    vendor/sony/loire-common-caf/proprietary/lib64/libloc_ds_api.so:system/lib64/libloc_ds_api.so \
    vendor/sony/loire-common-caf/proprietary/vendor/lib/libpreload-me.so:system/vendor/lib/libpreload-me.so \
    vendor/sony/loire-common-caf/proprietary/vendor/lib64/liblbs_core.so:system/vendor/lib64/liblbs_core.so \
    vendor/sony/loire-common-caf/proprietary/vendor/lib64/libpreload-me.so:system/vendor/lib64/libpreload-me.so
