# Copyright (C) 2012 Sony Mobile Communication
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_PACKAGES += \
	adsprpcd \
	irsc_util \
	mlog_qmi_service \
	msm_irqbalance \
	netmgrd \
	pm-proxy \
	pm-service \
	qseecomd \
	rmt_storage \
	sct_service \
	sensors \
	ta_qmi_service \
	tad_static \
	a530_gpmu \
	a530_pfp \
	a530_pm4 \
	a530_zap_b00 \
	a530_zap_b01 \
	a530_zap_b02 \
	a530_zap_elf \
	a530_zap_mdt \
	a530v1_pfp \
	a530v1_pm4 \
	a530v2_seq \
	a530v3_gpmu \
	a530v3_seq \
	cmnlib_b00 \
	cmnlib_b01 \
	cmnlib_b02 \
	cmnlib_b03 \
	cmnlib_b04 \
	cmnlib_b05 \
	cmnlib_mdt \
	cmnlib64_b00 \
	cmnlib64_b01 \
	cmnlib64_b02 \
	cmnlib64_b03 \
	cmnlib64_b04 \
	cmnlib64_b05 \
	cmnlib64_mdt \
	cpp_firmware_v1_10_0 \
	fidocfg_b00 \
	fidocfg_b01 \
	fidocfg_b02 \
	fidocfg_b03 \
	fidocfg_b04 \
	fidocfg_b05 \
	fidocfg_b06 \
	fidocfg_mdt \
	fidocrypto_b00 \
	fidocrypto_b01 \
	fidocrypto_b02 \
	fidocrypto_b03 \
	fidocrypto_b04 \
	fidocrypto_b05 \
	fidocrypto_b06 \
	fidocrypto_mdt \
	touch_module_id_0x90 \
	touch_module_id_0x91 \
	touch_module_id_0x92 \
	touch_module_id_0x93 \
	touch_module_id_0x94 \
	touch_module_id_0xb0 \
	touch_module_id_0xb1 \
	touch_module_id_0xb2 \
	touch_module_id_0xba \
	touch_module_id_0xbb \
	touch_module_id_0xbc \
	tzattest_b00 \
	tzattest_b01 \
	tzattest_b02 \
	tzattest_b03 \
	tzattest_b04 \
	tzattest_b05 \
	tzattest_b06 \
	tzattest_mdt \
	tzfingerprint_b00 \
	tzfingerprint_b01 \
	tzfingerprint_b02 \
	tzfingerprint_b03 \
	tzfingerprint_b04 \
	tzfingerprint_b05 \
	tzfingerprint_b06 \
	tzfingerprint_mdt \
	tzhdcp_b00 \
	tzhdcp_b01 \
	tzhdcp_b02 \
	tzhdcp_b03 \
	tzhdcp_b04 \
	tzhdcp_b05 \
	tzhdcp_b06 \
	tzhdcp_mdt \
	tzlibasb_b00 \
	tzlibasb_b01 \
	tzlibasb_b02 \
	tzlibasb_b03 \
	tzlibasb_b04 \
	tzlibasb_b05 \
	tzlibasb_b06 \
	tzlibasb_mdt \
	tzsuntory_b00 \
	tzsuntory_b01 \
	tzsuntory_b02 \
	tzsuntory_b03 \
	tzsuntory_b04 \
	tzsuntory_b05 \
	tzsuntory_b06 \
	tzsuntory_mdt \
	tztpm_b00 \
	tztpm_b01 \
	tztpm_b02 \
	tztpm_b03 \
	tztpm_b04 \
	tztpm_b05 \
	tztpm_b06 \
	tztpm_mdt \
	tzwidevine_b00 \
	tzwidevine_b01 \
	tzwidevine_b02 \
	tzwidevine_b03 \
	tzwidevine_b04 \
	tzwidevine_b05 \
	tzwidevine_b06 \
	tzwidevine_mdt \
	tzwvcpybuf_b00 \
	tzwvcpybuf_b01 \
	tzwvcpybuf_b02 \
	tzwvcpybuf_b03 \
	tzwvcpybuf_b04 \
	tzwvcpybuf_b05 \
	tzwvcpybuf_b06 \
	tzwvcpybuf_mdt \
	eglSubDriverAndroid \
	libEGL_adreno \
	libGLESv1_CM_adreno \
	libGLESv2_adreno \
	libQTapGLES \
	libq3dtools_adreno \
	libq3dtools_esx \
	gatekeeper_msm8996 \
	keystore_msm8996 \
	sensors_msm8996 \
	vulkan_msm8996 \
	libC2D2 \
	libCB \
	libOpenCL \
	libQSEEComAPI \
	libRSDriver_adreno \
	libacdb-fts \
	libacdbloader \
	libacdbmapper \
	libacdbrtac \
	libactuator_bu64747BS2 \
	libactuator_bu64747BS4 \
	libactuator_lc898217xc \
	libadiertac \
	libadreno_utils \
	libadsp_default_listener \
	libadsprpc \
	libaudcal \
	libaudioalsa \
	libc2d30-a3xx \
	libc2d30-a4xx \
	libc2d30-a5xx \
	libc2d30_bltlib \
	libchromaflash \
	libchromatix_imx214_common \
	libchromatix_imx214_cpp_liveshot \
	libchromatix_imx214_cpp_preview \
	libchromatix_imx214_cpp_snapshot \
	libchromatix_imx214_cpp_video \
	libchromatix_imx214_default_preview_lc898217 \
	libchromatix_imx214_default_video_lc898217 \
	libchromatix_imx214_postproc \
	libchromatix_imx214_preview \
	libchromatix_imx214_snapshot \
	libchromatix_imx214_video \
	libchromatix_imx258_common \
	libchromatix_imx258_cpp_liveshot \
	libchromatix_imx258_cpp_preview \
	libchromatix_imx258_cpp_snapshot \
	libchromatix_imx258_cpp_video \
	libchromatix_imx258_default_preview_lc898217 \
	libchromatix_imx258_default_video_lc898217 \
	libchromatix_imx258_postproc \
	libchromatix_imx258_preview \
	libchromatix_imx258_snapshot \
	libchromatix_imx258_video \
	libchromatix_imx300_common \
	libchromatix_imx300_cpp_liveshot \
	libchromatix_imx300_cpp_preview \
	libchromatix_imx300_cpp_snapshot \
	libchromatix_imx300_cpp_video \
	libchromatix_imx300_default_preview_bu64747 \
	libchromatix_imx300_default_video_bu64747 \
	libchromatix_imx300_postproc \
	libchromatix_imx300_preview \
	libchromatix_imx300_snapshot \
	libchromatix_imx400_common \
	libchromatix_imx400_cpp_liveshot \
	libchromatix_imx400_cpp_preview \
	libchromatix_imx400_cpp_snapshot \
	libchromatix_imx400_cpp_video \
	libchromatix_imx400_default_preview_bu64747 \
	libchromatix_imx400_default_video_bu64747 \
	libchromatix_imx400_postproc \
	libchromatix_imx400_preview \
	libchromatix_imx400_snapshot \
	libconfigdb \
	libdiag \
	libdrmfs \
	libdrmtime \
	libdsi_netctrl \
	libdsutils \
	libfastcvopt \
	libfastrpc_utf_stub \
	libfiltergenerator \
	libflash_pmic \
	libgsl \
	libidl \
	libjpegdhw \
	libjpegdmahw \
	libjpegehw \
	libllvm-glnext \
	libllvm-qcom \
	libllvm-qgl \
	liblqe \
	libmdmdetect \
	libmiscta \
	libmm-qdcm \
	libmmcamera2_c2d_module \
	libmmcamera2_cpp_module \
	libmmcamera2_frame_algorithm \
	libmmcamera2_iface_modules \
	libmmcamera2_imglib_modules \
	libmmcamera2_is \
	libmmcamera2_isp_modules \
	libmmcamera2_mct \
	libmmcamera2_mct_shimlayer \
	libmmcamera2_pp_buf_mgr \
	libmmcamera2_pproc_modules \
	libmmcamera2_q3a_core \
	libmmcamera2_sensor_modules \
	libmmcamera2_stats_algorithm \
	libmmcamera2_stats_lib \
	libmmcamera2_stats_modules \
	libmmcamera_chromaflash_lib \
	libmmcamera_dbg \
	libmmcamera_dummyalgo \
	libmmcamera_edgesmooth_lib \
	libmmcamera_eebinparse \
	libmmcamera_eeprom_util \
	libmmcamera_eztune_module \
	libmmcamera_facedetection_lib \
	libmmcamera_faceproc \
	libmmcamera_faceproc2 \
	libmmcamera_hdr_gb_lib \
	libmmcamera_hvx_add_constant \
	libmmcamera_hvx_grid_sum \
	libmmcamera_hvx_zzHDR \
	libmmcamera_imglib \
	libmmcamera_imglib_faceproc_adspstub \
	libmmcamera_imglib_faceproc_adspstub2 \
	libmmcamera_imx214 \
	libmmcamera_imx258 \
	libmmcamera_imx300 \
	libmmcamera_imx400 \
	libmmcamera_isp_abf47 \
	libmmcamera_isp_aec_bg_stats47 \
	libmmcamera_isp_bf_stats47 \
	libmmcamera_isp_bg_stats46 \
	libmmcamera_isp_bhist_stats44 \
	libmmcamera_isp_black_level47 \
	libmmcamera_isp_bpc47 \
	libmmcamera_isp_cac47 \
	libmmcamera_isp_chroma_enhan40 \
	libmmcamera_isp_chroma_suppress40 \
	libmmcamera_isp_clamp_encoder40 \
	libmmcamera_isp_clamp_video40 \
	libmmcamera_isp_clamp_viewfinder40 \
	libmmcamera_isp_color_correct46 \
	libmmcamera_isp_color_xform_encoder46 \
	libmmcamera_isp_color_xform_video46 \
	libmmcamera_isp_color_xform_viewfinder46 \
	libmmcamera_isp_cs_stats46 \
	libmmcamera_isp_demosaic47 \
	libmmcamera_isp_demux40 \
	libmmcamera_isp_fovcrop_encoder46 \
	libmmcamera_isp_fovcrop_video46 \
	libmmcamera_isp_fovcrop_viewfinder46 \
	libmmcamera_isp_gamma44 \
	libmmcamera_isp_gic46 \
	libmmcamera_isp_gtm46 \
	libmmcamera_isp_hdr46 \
	libmmcamera_isp_hdr_be_stats46 \
	libmmcamera_isp_ihist_stats46 \
	libmmcamera_isp_linearization40 \
	libmmcamera_isp_ltm47 \
	libmmcamera_isp_mce40 \
	libmmcamera_isp_mesh_rolloff44 \
	libmmcamera_isp_pedestal_correct46 \
	libmmcamera_isp_rs_stats46 \
	libmmcamera_isp_scaler_encoder46 \
	libmmcamera_isp_scaler_video46 \
	libmmcamera_isp_scaler_viewfinder46 \
	libmmcamera_isp_sce40 \
	libmmcamera_isp_snr47 \
	libmmcamera_isp_sub_module \
	libmmcamera_llvd \
	libmmcamera_optizoom_lib \
	libmmcamera_paaf_lib \
	libmmcamera_pdaf \
	libmmcamera_pdafcamif \
	libmmcamera_ppbase_module \
	libmmcamera_ppeiscore \
	libmmcamera_quadracfa \
	libmmcamera_sac_lib \
	libmmcamera_sat_dummy_lib \
	libmmcamera_stillmore_lib \
	libmmcamera_sw2d_lib \
	libmmcamera_thread_services \
	libmmcamera_tintless_algo \
	libmmcamera_tintless_bg_pca_algo \
	libmmcamera_trueportrait_lib \
	libmmcamera_tuning \
	libmmcamera_tuning_lookup \
	libmmcamera_ubifocus_lib \
	libmmjpeg \
	libmmqjpeg_codec \
	libmmqjpegdma \
	libnetmgr \
	libomx-dts \
	liboptizoom \
	libperipheral_client \
	libqcci_legacy \
	libqdi \
	libqdp \
	libqmi \
	libqmi_cci \
	libqmi_client_helper \
	libqmi_client_qmux \
	libqmi_common_so \
	libqmi_csi \
	libqmi_encdec \
	libqmiservices \
	libqmiservices_ext \
	libqomx_jpegdec \
	libqomx_jpegenc \
	libqomx_jpegenc_pipe \
	libremosaic_daemon \
	libril-qc-ltedirectdisc \
	libril-qc-qmi-1 \
	libril-qc-radioconfig \
	libril-qcril-hook-oem \
	librilqmiservices \
	librpmb \
	librs_adreno \
	librs_adreno_sha1 \
	libseemore \
	libsensor1 \
	libsensor_reg \
	libsettings \
	libsmemlog \
	libssd \
	libsystem_health_mon \
	libta \
	libtime_genoff \
	libtrueportrait \
	libubifocus \
	libxml
