# Copyright (C) 2012 Sony Mobile Communication
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_PACKAGES += \
	irsc_util \
	mlog_qmi_service \
	mm-qcamera-daemon \
	netmgrd \
	pm-proxy \
	pm-service \
	qmuxd \
	qseecomd \
	rmt_storage \
	sct_service \
	sensors \
	ta_qmi_service \
	tad_static \
	sensors.msm8974 \
	libQSEEComAPI \
	libactuator_bu64291g \
	libactuator_bu64295g \
	libactuator_bu64296g \
	libactuator_dw9719 \
	libadsprpc \
	libchromatix_imx132_common \
	libchromatix_imx132_cpp_liveshot \
	libchromatix_imx132_cpp_preview \
	libchromatix_imx132_cpp_snapshot \
	libchromatix_imx132_cpp_video \
	libchromatix_imx132_default_preview \
	libchromatix_imx132_default_video \
	libchromatix_imx132_liveshot \
	libchromatix_imx132_postproc \
	libchromatix_imx132_preview \
	libchromatix_imx132_snapshot \
	libchromatix_imx132_video \
	libchromatix_imx134_common \
	libchromatix_imx134_cpp_liveshot \
	libchromatix_imx134_cpp_preview \
	libchromatix_imx134_cpp_snapshot \
	libchromatix_imx134_cpp_video \
	libchromatix_imx134_default_preview_bu64291g \
	libchromatix_imx134_default_preview_dw9719 \
	libchromatix_imx134_default_video_bu64291g \
	libchromatix_imx134_default_video_dw9719 \
	libchromatix_imx134_liveshot \
	libchromatix_imx134_postproc \
	libchromatix_imx134_preview \
	libchromatix_imx134_snapshot \
	libchromatix_imx134_video \
	libchromatix_imx200_common \
	libchromatix_imx200_cpp_liveshot \
	libchromatix_imx200_cpp_preview \
	libchromatix_imx200_cpp_snapshot \
	libchromatix_imx200_cpp_video \
	libchromatix_imx200_default_preview_bu64295g \
	libchromatix_imx200_default_preview_bu64296g \
	libchromatix_imx200_default_video_bu64295g \
	libchromatix_imx200_default_video_bu64296g \
	libchromatix_imx200_liveshot \
	libchromatix_imx200_postproc \
	libchromatix_imx200_preview \
	libchromatix_imx200_snapshot \
	libchromatix_imx200_video \
	libconfigdb \
	libdiag \
	libdrmfs \
	libdrmtime \
	libdsi_netctrl \
	libdsutils \
	libflash_pmic \
	libidl \
	libjpegdhw \
	libjpegdmahw \
	libjpegehw \
	liblqe \
	libmdmdetect \
	libmiscta \
	libmmcamera2_c2d_module \
	libmmcamera2_cpp_module \
	libmmcamera2_iface_modules \
	libmmcamera2_imglib_modules \
	libmmcamera2_isp_modules \
	libmmcamera2_mct \
	libmmcamera2_pp_buf_mgr \
	libmmcamera2_pproc_modules \
	libmmcamera2_sensor_debug \
	libmmcamera2_sensor_modules \
	libmmcamera2_stats_modules \
	libmmcamera2_vpe_module \
	libmmcamera2_wnr_module \
	libmmcamera_csidtg \
	libmmcamera_eeprom_util \
	libmmcamera_eztune_module \
	libmmcamera_faceproc \
	libmmcamera_imglib \
	libmmcamera_imx132 \
	libmmcamera_imx134a \
	libmmcamera_imx134b \
	libmmcamera_imx200a \
	libmmcamera_imx200b \
	libmmcamera_isp_abf40 \
	libmmcamera_isp_bcc40 \
	libmmcamera_isp_be_stats44 \
	libmmcamera_isp_bf_stats40 \
	libmmcamera_isp_bg_stats44 \
	libmmcamera_isp_bhist_stats44 \
	libmmcamera_isp_bpc40 \
	libmmcamera_isp_chroma_enhan40 \
	libmmcamera_isp_chroma_suppress40 \
	libmmcamera_isp_clamp_encoder40 \
	libmmcamera_isp_clamp_video40 \
	libmmcamera_isp_clamp_viewfinder40 \
	libmmcamera_isp_color_correct40 \
	libmmcamera_isp_color_xform_encoder40 \
	libmmcamera_isp_color_xform_viewfinder40 \
	libmmcamera_isp_cs_stats44 \
	libmmcamera_isp_demosaic40 \
	libmmcamera_isp_demux40 \
	libmmcamera_isp_fovcrop_encoder40 \
	libmmcamera_isp_fovcrop_viewfinder40 \
	libmmcamera_isp_gamma40 \
	libmmcamera_isp_ihist_stats44 \
	libmmcamera_isp_linearization40 \
	libmmcamera_isp_luma_adaptation40 \
	libmmcamera_isp_mce40 \
	libmmcamera_isp_mesh_rolloff40 \
	libmmcamera_isp_rs_stats44 \
	libmmcamera_isp_scaler_encoder44 \
	libmmcamera_isp_scaler_viewfinder44 \
	libmmcamera_isp_sce40 \
	libmmcamera_isp_sub_module \
	libmmcamera_isp_wb40 \
	libmmcamera_ppbase_module \
	libmmcamera_thread_services \
	libmmcamera_tuning \
	libmmcamera_tuning_lookup \
	libmmcamera_vpu_module \
	libmmjpeg \
	libmmqjpeg_codec \
	libmmqjpegdma \
	libnetmgr \
	libperipheral_client \
	libqcci_legacy \
	libqdi \
	libqdp \
	libqmi \
	libqmi_cci \
	libqmi_client_helper \
	libqmi_client_qmux \
	libqmi_common_so \
	libqmi_csi \
	libqmi_encdec \
	libqmiservices \
	libqomx_jpegdec \
	libqomx_jpegenc \
	libqomx_jpegenc_pipe \
	libril-qc-qmi-1 \
	libril-qc-qmi-2 \
	libril-qcril-hook-oem \
	libsensor1 \
	libsensor_reg \
	libsmemlog \
	libsystem_health_mon \
	libta \
	libtime_genoff \
	libxml
