# Copyright (C) 2012 Sony Mobile Communication
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_PACKAGES += \
	irsc_util \
	mlog_qmi_service \
	mm-qcamera-daemon \
	msm_irqbalance \
	netmgrd \
	pm-proxy \
	pm-service \
	qmuxd \
	qseecomd \
	rmt_storage \
	sct_service \
	sensors \
	ta_qmi_service \
	tad_static \
	sensors.msm8952 \
	libQSEEComAPI \
	libactuator_bu64747gwz \
	libactuator_lc898217 \
	libadsprpc \
	libchromatix_imx214_common \
	libchromatix_imx214_cpp_liveshot \
	libchromatix_imx214_cpp_preview \
	libchromatix_imx214_cpp_snapshot \
	libchromatix_imx214_cpp_video \
	libchromatix_imx214_default_preview \
	libchromatix_imx214_default_video \
	libchromatix_imx214_liveshot \
	libchromatix_imx214_postproc \
	libchromatix_imx214_preview \
	libchromatix_imx214_snapshot \
	libchromatix_imx214_video \
	libchromatix_imx241_common \
	libchromatix_imx241_cpp_liveshot \
	libchromatix_imx241_cpp_preview \
	libchromatix_imx241_cpp_snapshot \
	libchromatix_imx241_cpp_video \
	libchromatix_imx241_default_preview \
	libchromatix_imx241_default_video \
	libchromatix_imx241_liveshot \
	libchromatix_imx241_postproc \
	libchromatix_imx241_preview \
	libchromatix_imx241_snapshot \
	libchromatix_imx241_video \
	libchromatix_imx300_common \
	libchromatix_imx300_cpp_liveshot \
	libchromatix_imx300_cpp_preview \
	libchromatix_imx300_cpp_snapshot \
	libchromatix_imx300_cpp_video \
	libchromatix_imx300_default_preview_bu64747gwz \
	libchromatix_imx300_default_video_bu64747gwz \
	libchromatix_imx300_liveshot \
	libchromatix_imx300_postproc \
	libchromatix_imx300_preview \
	libchromatix_imx300_snapshot \
	libchromatix_imx300_video \
	libconfigdb \
	libdiag \
	libdrmfs \
	libdrmtime \
	libdsi_netctrl \
	libdsutils \
	libflash_pmic \
	libidl \
	libjpegdhw \
	libjpegdmahw \
	libjpegehw \
	liblqe \
	libmdmdetect \
	libmiscta \
	libmmcamera2_c2d_module \
	libmmcamera2_cpp_module \
	libmmcamera2_iface_modules \
	libmmcamera2_imglib_modules \
	libmmcamera2_isp_modules \
	libmmcamera2_mct \
	libmmcamera2_pp_buf_mgr \
	libmmcamera2_pproc_modules \
	libmmcamera2_sensor_debug \
	libmmcamera2_sensor_modules \
	libmmcamera2_stats_modules \
	libmmcamera2_vpe_module \
	libmmcamera2_wnr_module \
	libmmcamera_csidtg \
	libmmcamera_eeprom_util \
	libmmcamera_eztune_module \
	libmmcamera_faceproc \
	libmmcamera_imglib \
	libmmcamera_imx214 \
	libmmcamera_imx241_1 \
	libmmcamera_imx300h \
	libmmcamera_imx300l \
	libmmcamera_isp_abcc44 \
	libmmcamera_isp_abf40 \
	libmmcamera_isp_bcc40 \
	libmmcamera_isp_be_stats44 \
	libmmcamera_isp_bf_stats47 \
	libmmcamera_isp_bg_stats44 \
	libmmcamera_isp_bhist_stats44 \
	libmmcamera_isp_bpc40 \
	libmmcamera_isp_chroma_enhan40 \
	libmmcamera_isp_chroma_suppress40 \
	libmmcamera_isp_clamp_encoder40 \
	libmmcamera_isp_clamp_video40 \
	libmmcamera_isp_clamp_viewfinder40 \
	libmmcamera_isp_color_correct40 \
	libmmcamera_isp_color_xform_encoder40 \
	libmmcamera_isp_color_xform_viewfinder40 \
	libmmcamera_isp_cs_stats44 \
	libmmcamera_isp_demosaic40 \
	libmmcamera_isp_demux40 \
	libmmcamera_isp_fovcrop_encoder40 \
	libmmcamera_isp_fovcrop_viewfinder40 \
	libmmcamera_isp_gamma40 \
	libmmcamera_isp_ihist_stats44 \
	libmmcamera_isp_linearization40 \
	libmmcamera_isp_ltm44 \
	libmmcamera_isp_luma_adaptation40 \
	libmmcamera_isp_mce40 \
	libmmcamera_isp_mesh_rolloff40 \
	libmmcamera_isp_rs_stats44 \
	libmmcamera_isp_scaler_encoder44 \
	libmmcamera_isp_scaler_viewfinder44 \
	libmmcamera_isp_sce40 \
	libmmcamera_isp_sub_module \
	libmmcamera_isp_wb40 \
	libmmcamera_ppbase_module \
	libmmcamera_thread_services \
	libmmcamera_tuning \
	libmmcamera_tuning_lookup \
	libmmcamera_vpu_module \
	libmmjpeg \
	libmmqjpeg_codec \
	libmmqjpegdma \
	libnetmgr \
	libperipheral_client \
	libqcci_legacy \
	libqdi \
	libqdp \
	libqmi \
	libqmi_cci \
	libqmi_client_helper \
	libqmi_client_qmux \
	libqmi_common_so \
	libqmi_csi \
	libqmi_encdec \
	libqmiservices \
	libqomx_jpegdec \
	libqomx_jpegenc \
	libqomx_jpegenc_pipe \
	libril-qc-qmi-1 \
	libril-qc-qmi-2 \
	libril-qcril-hook-oem \
	librpmb \
	libsensor1 \
	libsensor_reg \
	libsmemlog \
	libssd \
	libsystem_health_mon \
	libta \
	libtime_genoff \
	libxml \
	gatekeeper.msm8952 \
	keystore.msm8952 \
	sensors.msm8952 \
	libQSEEComAPI \
	libadsprpc \
	libconfigdb \
	libdiag \
	libdrmfs \
	libdrmtime \
	libdsi_netctrl \
	libdsutils \
	libidl \
	liblqe \
	libmdmdetect \
	libmiscta \
	libnetmgr \
	libperipheral_client \
	libqcci_legacy \
	libqdi \
	libqdp \
	libqmi \
	libqmi_cci \
	libqmi_client_helper \
	libqmi_client_qmux \
	libqmi_common_so \
	libqmi_csi \
	libqmi_encdec \
	libqmiservices \
	libril-qc-qmi-1 \
	libril-qc-qmi-2 \
	libril-qcril-hook-oem \
	librpmb \
	libsensor1 \
	libsensor_reg \
	libsmemlog \
	libssd \
	libsystem_health_mon \
	libta \
	libtime_genoff \
	libxml
