# Copyright (C) 2011-2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/shinano-leo-cafc/setup-makefiles.sh

PRODUCT_COPY_FILES += \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/Fluid/Fluid_Bluetooth_cal.acdb:system/etc/acdbdata/Fluid/Fluid_Bluetooth_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/Fluid/Fluid_General_cal.acdb:system/etc/acdbdata/Fluid/Fluid_General_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/Fluid/Fluid_Global_cal.acdb:system/etc/acdbdata/Fluid/Fluid_Global_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/Fluid/Fluid_Handset_cal.acdb:system/etc/acdbdata/Fluid/Fluid_Handset_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/Fluid/Fluid_Hdmi_cal.acdb:system/etc/acdbdata/Fluid/Fluid_Hdmi_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/Fluid/Fluid_Headset_cal.acdb:system/etc/acdbdata/Fluid/Fluid_Headset_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/Fluid/Fluid_Speaker_cal.acdb:system/etc/acdbdata/Fluid/Fluid_Speaker_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/Liquid/Liquid_Bluetooth_cal.acdb:system/etc/acdbdata/Liquid/Liquid_Bluetooth_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/Liquid/Liquid_General_cal.acdb:system/etc/acdbdata/Liquid/Liquid_General_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/Liquid/Liquid_Global_cal.acdb:system/etc/acdbdata/Liquid/Liquid_Global_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/Liquid/Liquid_Handset_cal.acdb:system/etc/acdbdata/Liquid/Liquid_Handset_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/Liquid/Liquid_Hdmi_cal.acdb:system/etc/acdbdata/Liquid/Liquid_Hdmi_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/Liquid/Liquid_Headset_cal.acdb:system/etc/acdbdata/Liquid/Liquid_Headset_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/Liquid/Liquid_Speaker_cal.acdb:system/etc/acdbdata/Liquid/Liquid_Speaker_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:system/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/MTP/MTP_General_cal.acdb:system/etc/acdbdata/MTP/MTP_General_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/MTP/MTP_Global_cal.acdb:system/etc/acdbdata/MTP/MTP_Global_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:system/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/MTP/MTP_Headset_cal.acdb:system/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/Sony/Sony_Bluetooth_cal.acdb:system/etc/acdbdata/Sony/Sony_Bluetooth_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/Sony/Sony_General_cal.acdb:system/etc/acdbdata/Sony/Sony_General_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/Sony/Sony_Global_cal.acdb:system/etc/acdbdata/Sony/Sony_Global_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/Sony/Sony_Handset_cal.acdb:system/etc/acdbdata/Sony/Sony_Handset_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/Sony/Sony_Hdmi_cal.acdb:system/etc/acdbdata/Sony/Sony_Hdmi_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/Sony/Sony_Headset_cal.acdb:system/etc/acdbdata/Sony/Sony_Headset_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/acdbdata/Sony/Sony_Speaker_cal.acdb:system/etc/acdbdata/Sony/Sony_Speaker_cal.acdb \
	vendor/sony/shinano-z3-caf/proprietary/etc/firmware/BCM43xx.hcd:system/etc/firmware/BCM43xx.hcd \
	vendor/sony/shinano-z3-caf/proprietary/etc/firmware/mba.b00:system/etc/firmware/mba.b00 \
	vendor/sony/shinano-z3-caf/proprietary/etc/firmware/mba.mdt:system/etc/firmware/mba.mdt \
	vendor/sony/shinano-z3-caf/proprietary/etc/firmware/tzhdcp.b00:system/etc/firmware/tzhdcp.b00 \
	vendor/sony/shinano-z3-caf/proprietary/etc/firmware/tzhdcp.b01:system/etc/firmware/tzhdcp.b01 \
	vendor/sony/shinano-z3-caf/proprietary/etc/firmware/tzhdcp.b02:system/etc/firmware/tzhdcp.b02 \
	vendor/sony/shinano-z3-caf/proprietary/etc/firmware/tzhdcp.b03:system/etc/firmware/tzhdcp.b03 \
	vendor/sony/shinano-z3-caf/proprietary/etc/firmware/tzhdcp.flist:system/etc/firmware/tzhdcp.flist \
	vendor/sony/shinano-z3-caf/proprietary/etc/firmware/tzhdcp.mdt:system/etc/firmware/tzhdcp.mdt \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/btm.speaker:system/etc/tfa98xx/btm.speaker \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/coldboot.patch:system/etc/tfa98xx/coldboot.patch \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/FMSpeaker_btm.eq:system/etc/tfa98xx/FMSpeaker_btm.eq \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/FMSpeaker_btm.preset:system/etc/tfa98xx/FMSpeaker_btm.preset \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/FMSpeaker_top.eq:system/etc/tfa98xx/FMSpeaker_top.eq \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/FMSpeaker_top.preset:system/etc/tfa98xx/FMSpeaker_top.preset \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/HiFiSpeaker_btm.eq:system/etc/tfa98xx/HiFiSpeaker_btm.eq \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/HiFiSpeaker_btm.preset:system/etc/tfa98xx/HiFiSpeaker_btm.preset \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/HiFiSpeakerRing_btm.eq:system/etc/tfa98xx/HiFiSpeakerRing_btm.eq \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/HiFiSpeakerRing_btm.preset:system/etc/tfa98xx/HiFiSpeakerRing_btm.preset \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/HiFiSpeakerRing_top.eq:system/etc/tfa98xx/HiFiSpeakerRing_top.eq \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/HiFiSpeakerRing_top.preset:system/etc/tfa98xx/HiFiSpeakerRing_top.preset \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/HiFiSpeakerSforce_btm.eq:system/etc/tfa98xx/HiFiSpeakerSforce_btm.eq \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/HiFiSpeakerSforce_btm.preset:system/etc/tfa98xx/HiFiSpeakerSforce_btm.preset \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/HiFiSpeakerSforce_top.eq:system/etc/tfa98xx/HiFiSpeakerSforce_top.eq \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/HiFiSpeakerSforce_top.preset:system/etc/tfa98xx/HiFiSpeakerSforce_top.preset \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/HiFiSpeaker_top.eq:system/etc/tfa98xx/HiFiSpeaker_top.eq \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/HiFiSpeaker_top.preset:system/etc/tfa98xx/HiFiSpeaker_top.preset \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/TFA9890_btm.config:system/etc/tfa98xx/TFA9890_btm.config \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/TFA9890.patch:system/etc/tfa98xx/TFA9890.patch \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/TFA9890_Receiver.config:system/etc/tfa98xx/TFA9890_Receiver.config \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/TFA9890_top.config:system/etc/tfa98xx/TFA9890_top.config \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/top.speaker:system/etc/tfa98xx/top.speaker \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/VoiceCallEarpice_top.eq:system/etc/tfa98xx/VoiceCallEarpice_top.eq \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/VoiceCallEarpice_top.preset:system/etc/tfa98xx/VoiceCallEarpice_top.preset \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/VoiceCallSpeaker_btm.eq:system/etc/tfa98xx/VoiceCallSpeaker_btm.eq \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/VoiceCallSpeaker_btm.preset:system/etc/tfa98xx/VoiceCallSpeaker_btm.preset \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/VoiceCallSpeaker_top.eq:system/etc/tfa98xx/VoiceCallSpeaker_top.eq \
	vendor/sony/shinano-z3-caf/proprietary/etc/tfa98xx/VoiceCallSpeaker_top.preset:system/etc/tfa98xx/VoiceCallSpeaker_top.preset \
	vendor/sony/shinano-z3-caf/proprietary/usr/idc/clearpad.idc:system/usr/idc/clearpad.idc

#Camera specific files
PRODUCT_COPY_FILES += \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/product_CACAO.dat:system/vendor/camera/product_CACAO.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/product.dat:system/vendor/camera/product.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/cam_ctrl.dat:system/vendor/camera/SEM02BN1/cam_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/cap_ctrl.dat:system/vendor/camera/SEM02BN1/cap_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/chokoball.dat:system/vendor/camera/SEM02BN1/chokoball.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/color_ctrl.dat:system/vendor/camera/SEM02BN1/color_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/dataflow.dat:system/vendor/camera/SEM02BN1/dataflow.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/debug_mgr.dat:system/vendor/camera/SEM02BN1/debug_mgr.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/exposure_ctrl.dat:system/vendor/camera/SEM02BN1/exposure_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/face_detector.dat:system/vendor/camera/SEM02BN1/face_detector.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/flicker_detector.dat:system/vendor/camera/SEM02BN1/flicker_detector.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/focus_stats_conv.dat:system/vendor/camera/SEM02BN1/focus_stats_conv.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/hal_ctrl.dat:system/vendor/camera/SEM02BN1/hal_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/hal_ctrl_platform.dat:system/vendor/camera/SEM02BN1/hal_ctrl_platform.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/hdr_comp.dat:system/vendor/camera/SEM02BN1/hdr_comp.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/idt_ctrl.dat:system/vendor/camera/SEM02BN1/idt_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/image_conv.dat:system/vendor/camera/SEM02BN1/image_conv.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/imgproc.dat:system/vendor/camera/SEM02BN1/imgproc.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1_IMX132.dat:system/vendor/camera/SEM02BN1_IMX132.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/jpeg_enc.dat:system/vendor/camera/SEM02BN1/jpeg_enc.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/lens_ctrl.dat:system/vendor/camera/SEM02BN1/lens_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/module.dat:system/vendor/camera/SEM02BN1/module.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/motion_estimation.dat:system/vendor/camera/SEM02BN1/motion_estimation.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/multiframe_nr.dat:system/vendor/camera/SEM02BN1/multiframe_nr.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/object_tracker.dat:system/vendor/camera/SEM02BN1/object_tracker.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/scene_detector.dat:system/vendor/camera/SEM02BN1/scene_detector.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/snapshot_ctrl.dat:system/vendor/camera/SEM02BN1/snapshot_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SEM02BN1/streaming_ctrl.dat:system/vendor/camera/SEM02BN1/streaming_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1_BU64296GWX.dat:system/vendor/camera/SOI20BS1_BU64296GWX.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/cam_ctrl.dat:system/vendor/camera/SOI20BS1/cam_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/cap_ctrl.dat:system/vendor/camera/SOI20BS1/cap_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/chokoball.dat:system/vendor/camera/SOI20BS1/chokoball.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/color_ctrl.dat:system/vendor/camera/SOI20BS1/color_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/dataflow.dat:system/vendor/camera/SOI20BS1/dataflow.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/debug_mgr.dat:system/vendor/camera/SOI20BS1/debug_mgr.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/exposure_ctrl.dat:system/vendor/camera/SOI20BS1/exposure_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/face_detector.dat:system/vendor/camera/SOI20BS1/face_detector.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/flicker_detector.dat:system/vendor/camera/SOI20BS1/flicker_detector.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/focus_stats_conv.dat:system/vendor/camera/SOI20BS1/focus_stats_conv.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/hal_ctrl.dat:system/vendor/camera/SOI20BS1/hal_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/hal_ctrl_platform.dat:system/vendor/camera/SOI20BS1/hal_ctrl_platform.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/hdr_comp.dat:system/vendor/camera/SOI20BS1/hdr_comp.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/idt_ctrl.dat:system/vendor/camera/SOI20BS1/idt_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/image_conv.dat:system/vendor/camera/SOI20BS1/image_conv.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/imgproc.dat:system/vendor/camera/SOI20BS1/imgproc.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1_IMX200.dat:system/vendor/camera/SOI20BS1_IMX200.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/jpeg_enc.dat:system/vendor/camera/SOI20BS1/jpeg_enc.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/lens_ctrl.dat:system/vendor/camera/SOI20BS1/lens_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/module.dat:system/vendor/camera/SOI20BS1/module.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/motion_estimation.dat:system/vendor/camera/SOI20BS1/motion_estimation.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/multiframe_nr.dat:system/vendor/camera/SOI20BS1/multiframe_nr.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/object_tracker.dat:system/vendor/camera/SOI20BS1/object_tracker.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/scene_detector.dat:system/vendor/camera/SOI20BS1/scene_detector.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/snapshot_ctrl.dat:system/vendor/camera/SOI20BS1/snapshot_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/SOI20BS1/streaming_ctrl.dat:system/vendor/camera/SOI20BS1/streaming_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1_IMX132.dat:system/vendor/camera/LGI02BN1_IMX132.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/cam_ctrl.dat:system/vendor/camera/LGI02BN1/cam_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/cap_ctrl.dat:system/vendor/camera/LGI02BN1/cap_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/chokoball.dat:system/vendor/camera/LGI02BN1/chokoball.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/color_ctrl.dat:system/vendor/camera/LGI02BN1/color_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/dataflow.dat:system/vendor/camera/LGI02BN1/dataflow.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/debug_mgr.dat:system/vendor/camera/LGI02BN1/debug_mgr.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/exposure_ctrl.dat:system/vendor/camera/LGI02BN1/exposure_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/face_detector.dat:system/vendor/camera/LGI02BN1/face_detector.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/flicker_detector.dat:system/vendor/camera/LGI02BN1/flicker_detector.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/focus_stats_conv.dat:system/vendor/camera/LGI02BN1/focus_stats_conv.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/hal_ctrl.dat:system/vendor/camera/LGI02BN1/hal_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/hal_ctrl_platform.dat:system/vendor/camera/LGI02BN1/hal_ctrl_platform.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/hdr_comp.dat:system/vendor/camera/LGI02BN1/hdr_comp.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/idt_ctrl.dat:system/vendor/camera/LGI02BN1/idt_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/image_conv.dat:system/vendor/camera/LGI02BN1/image_conv.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/imgproc.dat:system/vendor/camera/LGI02BN1/imgproc.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/jpeg_enc.dat:system/vendor/camera/LGI02BN1/jpeg_enc.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/lens_ctrl.dat:system/vendor/camera/LGI02BN1/lens_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/module.dat:system/vendor/camera/LGI02BN1/module.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/motion_estimation.dat:system/vendor/camera/LGI02BN1/motion_estimation.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/multiframe_nr.dat:system/vendor/camera/LGI02BN1/multiframe_nr.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/object_tracker.dat:system/vendor/camera/LGI02BN1/object_tracker.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/scene_detector.dat:system/vendor/camera/LGI02BN1/scene_detector.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/snapshot_ctrl.dat:system/vendor/camera/LGI02BN1/snapshot_ctrl.dat \
	vendor/sony/shinano-z3-caf/proprietary/vendor/camera/LGI02BN1/streaming_ctrl.dat:system/vendor/camera/LGI02BN1/streaming_ctrl.dat

# Modem specific files: 
# dsds = dual SIM
# ets = single SIM
PRODUCT_COPY_FILES += \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_dsds.b00:system/vendor/etc/firmware/adsp_leo_dsds.b00 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_dsds.b01:system/vendor/etc/firmware/adsp_leo_dsds.b01 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_dsds.b02:system/vendor/etc/firmware/adsp_leo_dsds.b02 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_dsds.b03:system/vendor/etc/firmware/adsp_leo_dsds.b03 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_dsds.b04:system/vendor/etc/firmware/adsp_leo_dsds.b04 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_dsds.b05:system/vendor/etc/firmware/adsp_leo_dsds.b05 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_dsds.b06:system/vendor/etc/firmware/adsp_leo_dsds.b06 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_dsds.b07:system/vendor/etc/firmware/adsp_leo_dsds.b07 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_dsds.b08:system/vendor/etc/firmware/adsp_leo_dsds.b08 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_dsds.b09:system/vendor/etc/firmware/adsp_leo_dsds.b09 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_dsds.b10:system/vendor/etc/firmware/adsp_leo_dsds.b10 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_dsds.b11:system/vendor/etc/firmware/adsp_leo_dsds.b11 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_dsds.b12:system/vendor/etc/firmware/adsp_leo_dsds.b12 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_dsds.mdt:system/vendor/etc/firmware/adsp_leo_dsds.mdt \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_ets.b00:system/vendor/etc/firmware/adsp_leo_ets.b00 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_ets.b01:system/vendor/etc/firmware/adsp_leo_ets.b01 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_ets.b02:system/vendor/etc/firmware/adsp_leo_ets.b02 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_ets.b03:system/vendor/etc/firmware/adsp_leo_ets.b03 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_ets.b04:system/vendor/etc/firmware/adsp_leo_ets.b04 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_ets.b05:system/vendor/etc/firmware/adsp_leo_ets.b05 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_ets.b06:system/vendor/etc/firmware/adsp_leo_ets.b06 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_ets.b07:system/vendor/etc/firmware/adsp_leo_ets.b07 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_ets.b08:system/vendor/etc/firmware/adsp_leo_ets.b08 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_ets.b09:system/vendor/etc/firmware/adsp_leo_ets.b09 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_ets.b10:system/vendor/etc/firmware/adsp_leo_ets.b10 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_ets.b11:system/vendor/etc/firmware/adsp_leo_ets.b11 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_ets.b12:system/vendor/etc/firmware/adsp_leo_ets.b12 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/adsp_leo_ets.mdt:system/vendor/etc/firmware/adsp_leo_ets.mdt \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_dsds.b00:system/vendor/etc/firmware/modem_leo_dsds.b00 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_dsds.b01:system/vendor/etc/firmware/modem_leo_dsds.b01 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_dsds.b02:system/vendor/etc/firmware/modem_leo_dsds.b02 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_dsds.b03:system/vendor/etc/firmware/modem_leo_dsds.b03 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_dsds.b06:system/vendor/etc/firmware/modem_leo_dsds.b06 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_dsds.b08:system/vendor/etc/firmware/modem_leo_dsds.b08 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_dsds.b09:system/vendor/etc/firmware/modem_leo_dsds.b09 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_dsds.b11:system/vendor/etc/firmware/modem_leo_dsds.b11 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_dsds.b12:system/vendor/etc/firmware/modem_leo_dsds.b12 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_dsds.b13:system/vendor/etc/firmware/modem_leo_dsds.b13 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_dsds.b14:system/vendor/etc/firmware/modem_leo_dsds.b14 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_dsds.b15:system/vendor/etc/firmware/modem_leo_dsds.b15 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_dsds.b16:system/vendor/etc/firmware/modem_leo_dsds.b16 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_dsds.b17:system/vendor/etc/firmware/modem_leo_dsds.b17 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_dsds.b18:system/vendor/etc/firmware/modem_leo_dsds.b18 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_dsds.b19:system/vendor/etc/firmware/modem_leo_dsds.b19 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_dsds.b22:system/vendor/etc/firmware/modem_leo_dsds.b22 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_dsds.b23:system/vendor/etc/firmware/modem_leo_dsds.b23 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_dsds.b24:system/vendor/etc/firmware/modem_leo_dsds.b24 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_dsds.b25:system/vendor/etc/firmware/modem_leo_dsds.b25 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_dsds.mdt:system/vendor/etc/firmware/modem_leo_dsds.mdt \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_ets.b00:system/vendor/etc/firmware/modem_leo_ets.b00 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_ets.b01:system/vendor/etc/firmware/modem_leo_ets.b01 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_ets.b02:system/vendor/etc/firmware/modem_leo_ets.b02 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_ets.b03:system/vendor/etc/firmware/modem_leo_ets.b03 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_ets.b06:system/vendor/etc/firmware/modem_leo_ets.b06 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_ets.b08:system/vendor/etc/firmware/modem_leo_ets.b08 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_ets.b09:system/vendor/etc/firmware/modem_leo_ets.b09 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_ets.b11:system/vendor/etc/firmware/modem_leo_ets.b11 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_ets.b12:system/vendor/etc/firmware/modem_leo_ets.b12 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_ets.b13:system/vendor/etc/firmware/modem_leo_ets.b13 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_ets.b14:system/vendor/etc/firmware/modem_leo_ets.b14 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_ets.b15:system/vendor/etc/firmware/modem_leo_ets.b15 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_ets.b16:system/vendor/etc/firmware/modem_leo_ets.b16 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_ets.b17:system/vendor/etc/firmware/modem_leo_ets.b17 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_ets.b18:system/vendor/etc/firmware/modem_leo_ets.b18 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_ets.b19:system/vendor/etc/firmware/modem_leo_ets.b19 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_ets.b22:system/vendor/etc/firmware/modem_leo_ets.b22 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_ets.b23:system/vendor/etc/firmware/modem_leo_ets.b23 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_ets.b24:system/vendor/etc/firmware/modem_leo_ets.b24 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_ets.b25:system/vendor/etc/firmware/modem_leo_ets.b25 \
	vendor/sony/shinano-z3-caf/proprietary/vendor/etc/firmware/modem_leo_ets.mdt:system/vendor/etc/firmware/modem_leo_ets.mdt

